[build]
  publish = "build/client"
  command = "pnpm run build:all"

[dev]
  command = "react-router dev --port 5174"
  targetPort = 5174
  framework = "#custom"
  port = 8888

[[edge_functions]]
  function = "vibe-meta"
  path = "/vibe/*"

[[edge_functions]]
  function = "vibe-meta"
  path = "/firehose"

# Storybook SPA routing - serve index.html for storybook routes
[[redirects]]
  from = "/storybook"
  to = "/storybook/index.html"
  status = 200

# Storybook assets and sub-routes
[[redirects]]
  from = "/storybook/*"
  to = "/storybook/:splat"
  status = 200

# Main app catch-all routing (must come after storybook redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS headers for openai-image edge function
[[headers]]
  for = "/api/openai-image/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"

# No caching for Netlify system files
[[headers]]
  for = "/.netlify/*"
  [headers.values]
    Cache-Control = "no-store, no-cache"

# HTML files - revalidate but allow serving stale during revalidation
# This applies to all route paths in your SPA
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# JavaScript files with content hashes - immutable and long cache
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CSS files with content hashes - immutable and long cache
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image files - immutable and long cache
[[headers]]
  for = "/assets/*.(png|jpg|jpeg|gif|webp|svg|ico)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Fonts - immutable and long cache
[[headers]]
  for = "/assets/*.(woff|woff2|ttf|otf|eot)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Storybook HTML files - revalidate but allow serving stale during revalidation
[[headers]]
  for = "/storybook/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Storybook JavaScript files - immutable and long cache
[[headers]]
  for = "/storybook/static/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Storybook CSS files - immutable and long cache
[[headers]]
  for = "/storybook/static/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Storybook assets - immutable and long cache
[[headers]]
  for = "/storybook/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CORS headers for vibes.diy resources
[[headers]]
  for = "https://vibes.diy/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Max-Age = "86400"
