packages:
  - "call-ai/base"
  - "call-ai/pkg"
  - "call-ai/v2"
  - "call-ai/tests/unit"
  - "call-ai/tests/integration"
  - "call-ai/tests/helpers"
  - "use-vibes/types"
  - "use-vibes/base"
  - "use-vibes/pkg"
  - "use-vibes/tests"
  - "use-vibes/examples/react-example"
  - "use-vibes/examples/hosted-dev"
  - "vibes.diy/pkg"
  - "vibes.diy/tempo"
  - "vibes.diy/tests/app"
  - "vibes.diy/tests/simple-chat"
  - "vibes.diy/failback-homepage"
  - "prompts/pkg"
  - "prompts/tests"
  - "hosting/base"
  - "hosting/pkg"
  - "hosting/tests/unit"
  - "utils/pkg"
  - "utils/tests"

# Override sharp version to avoid build failures with 0.34.x
overrides:
  sharp: 0.33.5

# Avoid needing to interactively run 'pnpm approve-build' step during quickstart
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "core-js"
  - "es5-ext"
  - "esbuild"
  - "netlify"
  - "netlify-cli"
  - "playwright-chromium"
  - "sharp"
  - "unix-dgram"
  - "unrs-resolver"
  - "workerd"
