#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/landing-pages/vibes/party-scorekeepers"
cd "$HERE"
gen() { local slug="$1"; shift; ( "$TSX" "$MAIN" generate --app-slug "$slug" "$*" >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) & }
: > "$HERE/_status.log"

gen "farkle-house-rules" "Build a single-file React Farkle scorekeeper for up to 6 named players, target 10000 points. Use useFireproof from the imported 'use-fireproof' hook for live multi-device sync of game state, rounds, and scores. Persist the active player roster and house-rule toggle preferences to localStorage so the same browser remembers its crew between sessions. Add toggleable house-rule variants that affect scoring math: count three pairs as 1500, count straight (1-2-3-4-5-6) as 1500, four-of-a-kind multiplier ×2 instead of ×4, optional 'lose everything if you score zero on a turn' rule, optional 'must enter at 500' rule. Each turn: track current-turn running tally as the player accumulates rolls before lock-in, with a big visible 'Bank' button and a 'Hot Dice' indicator that lights up when all six dice score. Round-by-round entry log with undo. Mobile-friendly chunky buttons, large numerals. No external libraries beyond React and use-fireproof."

gen "yahtzee-cousin-edition" "Build a single-file React Yahtzee scorekeeper called 'Yahtzee Cousin Edition' for 2-6 named players. Use useFireproof from 'use-fireproof' for live cross-device sync of the scorecard. Persist player names and house-rule choices in localStorage per browser. Render the standard 13-category scorecard (ones through sixes with upper bonus at 63, three-of-a-kind, four-of-a-kind, full house, small straight, large straight, Yahtzee, chance) as a tappable grid where you enter scores per round. Include a sidebar of toggleable house-rule overrides: joker rules on/off for bonus Yahtzees, full-house = 30 vs 25, allow five-of-a-kind bonus (extra 50), allow stacking small-straight credit on chance row. Show running totals, upper-section progress toward bonus, and final winner. Mobile-friendly tap targets, sticky header with current round."

gen "spades-scoresheet" "Build a single-file React Spades scoresheet for partner-pair (2v2) play. Use useFireproof from 'use-fireproof' for live sync so both teams see the same sheet. Persist the four named players (two teams of two) and team names to localStorage per browser. Per hand: enter each team's bid, each team's tricks taken, and any nil/blind-nil declarations. Auto-calculate score per standard rules: bid made = bid×10 + 1 per overtrick (bag), bid missed = -bid×10, nil success = +100, nil fail = -100, blind nil ±200. Apply bag penalty: every 10 bags accumulated subtracts 100 from team total. Show running totals, bag counter per team, hand-by-hand log with edit/undo. Mobile-friendly two-column layout for the two teams, big numeric inputs."

gen "cribbage-virtual-board" "Build a single-file React virtual cribbage peg board for 2 players (or two teams). Use useFireproof from 'use-fireproof' for live sync of peg positions and hand history. Persist the two player names to localStorage per browser. Render a classic two-track 121-hole peg board as SVG with two pegs per player (front and rear) and animate peg advances when points are awarded. Add a per-hand entry panel: input points scored this hand, tap to advance, the rear peg jumps past the front peg with a smooth transition. Include toggleable optional rules: 'muggins' (claim missed points from opponent) with a one-tap claim button, automatic 'skunk' detection (winner finishes before loser passes the skunk line at 91), and 'match' series tracking across multiple games to a best-of total. Mobile-friendly tall layout, big tap-to-advance buttons."

gen "mahjong-scoresheet" "Build a single-file React 4-player mahjong session scoresheet. Use useFireproof from 'use-fireproof' for live sync so all four seats see the same running totals. Persist seat names (East, South, West, North) and player names to localStorage per browser. Per hand: pick the winner (or 'draw'), enter the hand value in faan/han, choose how the losers settle (self-draw splits among three losers vs discard means the discarder pays full). Include a toggle for 'East doubled' rule (East wins or pays double). Auto-compute each player's net change per hand and roll into session totals across many hands. Show a hand-by-hand log with timestamps, current dealer (East rotation), prevailing wind indicator, and a session summary. Mobile-friendly four-quadrant scoreboard view."

wait
echo "ALL DONE" >> "$HERE/_status.log"
