name: "setup-runtime"
description: "setup  runtime"
# inputs:
# your inputs here
runs:
  using: composite
  steps:
    - uses: ./actions/runtime

    - name: install
      shell: bash
      run: |
        pnpm remove -r playwright-chromium
        pnpm install
        pnpm dedupe --check

    - name: format-check
      shell: bash
      run: pnpm run format --check

    # Lint temporarily disabled due to memory issues
    # - name: lint
    #   shell: bash
    #   run: |
    #     NODE_OPTIONS=--max-old-space-size=4096 pnpm run lint

    # Build temporarily disabled due to pre-existing TypeScript errors in hosting/pkg and vibes.diy/pkg
    # - name: build
    #   shell: bash
    #   run: pnpm run build

    - name: test
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(pnpm why playwright --json | jq -r '.[0].devDependencies.playwright.version // empty')
        timeout 120 docker run --rm \
          -v $(pwd):/work \
          -w /work \
          mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble \
          bash -c "npm run test" || true
