name: "setup-runtime"
description: "setup  runtime"
# inputs:
# your inputs here
runs:
  using: composite
  steps:
    - uses: ./actions/runtime

    - name: install
      shell: bash
      run: pnpm install

    - name: format-check
      shell: bash
      run: pnpm run format --check

    - name: lint
      shell: bash
      run: |
        pnpm run lint

    - name: build
      shell: bash
      run: pnpm run build

    - name: playwright
      shell: bash
      run: |
        apt-get update
        apt-get install -y ca-certificates curl gnupg lsb-release jq rsync
        # Add Docker's official GPG key
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        # Set up Docker repository
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        # Install Docker Compose plugin
        apt-get update
        apt-get install -y docker-ce-cli docker-compose-plugin
        docker ps
        docker compose version
        pnpm exec playwright --version
        git config --global --add safe.directory $(pwd)

    # - name: install playwright browsers
    #   shell: bash
    #   run: pnpm exec playwright install chromium --with-deps

    - name: test
      shell: bash
      run: pnpm run test
