name: "setup-runtime"
description: "setup  runtime"
# inputs:
# your inputs here
runs:
  using: composite
  steps:
    - uses: ./actions/runtime

    - name: install
      shell: bash
      run: pnpm install

    - name: format-check
      shell: bash
      run: pnpm run format --check

    - name: lint
      shell: bash
      run: |
        pnpm run lint

    - name: build
      shell: bash
      run: pnpm run build

    - name: install playwright browsers
      shell: bash
      run: pnpm exec playwright install chromium --with-deps

    - name: test
      shell: bash
      run: pnpm run test
