name: "setup-runtime"
description: "setup  runtime"
# inputs:
# your inputs here
runs:
  using: composite
  steps:
    - uses: ./actions/runtime

    - name: install
      shell: bash
      run: pnpm install
    - name: format-check
      shell: bash
      run: pnpm run format --check
    - name: lint
      shell: bash
      run: pnpm run lint

    - name: install
      shell: bash
      run: pnpm install

    - name: build
      shell: bash
      run: pnpm run build

#    - name: playwright
#      shell: bash
#      run: |
#        pnpm exec playwright install chromium --with-deps

    - name: test Attempt 1
      shell: bash
      env:
        FP_CI: fp_ci
      id: attempt1
      continue-on-error: true
      run: pnpm run test

    - name: test Attempt 2
      shell: bash
      env:
        FP_CI: fp_ci
      if: steps.attempt1.outcome == 'failure'
      run: pnpm run test

