#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/landing-pages/vibes/college"
cd "$HERE"

# Pin the publishing namespace explicitly so a stale `vibes-diy login`
# default (account swap, re-auth, CLI upgrade) cannot land deploys at the
# wrong user-slug. See src/pages/featured-apps/README.md for context.
USER_SLUG="og"

STYLE='STYLE — Slab Concrete. Load Google Fonts: Inter, JetBrains Mono (display=optional). Body Inter 1rem; mono labels in JetBrains Mono. Background concrete oklch(0.88 0 0) (warm raw concrete grey). Foreground black oklch(0.10 0 0). Accent acid oklch(0.94 0.23 110) (highlighter neon-yellow) — use sparingly for emphasis: pull-quote backgrounds, current state markers, hover-fills on buttons. Borders 2px solid black. Sharp corners. Layout: single-column max-width 880px with strict slab sections separated by thick black rules. Headlines in Inter font-weight 900, uppercase, letter-spacing -0.02em, mixed-case allowed for big titles. Small labels JetBrains Mono uppercase 0.55-0.7rem letter-spacing 0.15em. Buttons: 2px solid black, white bg, black text, hover fills with acid yellow (text stays black). Inputs: bottom-bordered only (border:none; border-bottom: 2px solid black). The aesthetic is a textbook page with a thick yellow highlighter scrawled across one passage. Single-file React with useFireproof; persist as Fireproof docs and render past entries below the live form.'

gen() {
  local slug="$1"; shift
  local prompt="$*"
  ( "$TSX" "$MAIN" generate --user-slug "$USER_SLUG" --app-slug "$slug" "$prompt" >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) &
}

: > "$HERE/_status.log"

gen lonely-socks-club 'Build a playful social app called Lonely Socks Club where people post photos of single lonely socks searching for their soulmate after getting separated in the laundry. The emotional tone should parody dramatic dating apps and heartfelt reunion stories. Every sock should feel like a tiny abandoned character with hopes and dreams. The app should encourage users to upload photos of unmatched socks, give them funny names, write exaggerated bios, and browse possible matches from nearby dorms, apartments, or friend groups. When two socks are reunited, the app should celebrate with absurd emotional language like a reality TV dating finale or a wedding announcement. The UI should feel warm, funny, and slightly overdramatic, like a combination of a dating app, a pet adoption page, and a support group for laundry tragedy survivors. Encourage sharing, reactions, comments, and dramatic AI-generated narration about the loneliness of the sock and its quest for completion. The whole experience should feel low stakes, communal, weirdly wholesome, and immediately understandable to exhausted college students doing laundry at 1am. $STYLE'

gen captain-safety-meeting 'Build a lightweight coordination app called Captain Safety Meeting that helps friend groups find the best overlapping time for spontaneous hangouts, late-night smoke sessions, rooftop chats, game breaks, or other vaguely-defined college rituals. The joke is that everyone knows what a safety meeting means but nobody says it out loud directly. The app should feel casual, funny, slightly conspiratorial, and extremely frictionless. Users should be able to quickly mark when they are free without creating a complicated schedule. The system should feel like a magical social coordinator that instantly figures out the best moment for the crew to assemble. The visual tone should feel like dorm-room logistics meets pirate captain energy meets student-group chaos. Include playful language about assembling the crew, syncing the squad, finding the sacred overlap, or getting the gang together before someone falls asleep. The app should make group scheduling feel social and fun instead of corporate and annoying. Avoid anything that feels like a work calendar or enterprise scheduling software. $STYLE'

gen professor-pizza 'Build a competitive study-group app called Professor Pizza where everyone submits their preferred pizza order before participating in a short trivia battle or pop quiz related to the study topic. Whoever performs best gets the strongest influence over the final pizza decision. The app should feel like a combination of a game show, a study session, and a dorm-room democracy. The emotional experience should reward people for actually knowing the material while still feeling silly and social. The app should encourage playful rivalry, dramatic reveal moments, and strong opinions about toppings. The interface should feel bright, energetic, and built for stressed students trying to turn studying into a social ritual instead of a chore. Include opportunities for people to vote, trash talk lightly, celebrate victories, and mourn terrible topping outcomes. The AI personality should narrate the quiz results like a dramatic academic sports announcer. The whole point is making studying feel like a communal game with food stakes. $STYLE'

gen study-roulette 'Build a social productivity app called Study Roulette where students can mark themselves as ready to study and get randomly paired or grouped with other nearby students for short timed work sessions. The app should feel spontaneous, social, and slightly chaotic in a good way, like speed dating for productivity. It should support quick pairings, temporary study circles, themed sessions, accountability bursts, and low-pressure social studying. Some people may secretly hope to meet someone interesting, while others genuinely just need motivation to focus, and the app should comfortably support both energies without becoming a dating app. The atmosphere should feel alive and communal, like late-night library culture during finals week. Include visual indicators that show who is currently active, what subjects people are working on, and what kind of energy they want, like silent focus mode versus collaborative chaos mode. The app should celebrate streaks, accidental friendships, and the strange temporary intimacy of studying beside strangers. $STYLE'

gen clean-deputy 'Build a funny anonymous community app called Clean Deputy where people can quietly report annoying shared-space situations like abandoned laundry, disgusting fridges, mystery spills, moldy leftovers, unwashed dishes, destroyed bathrooms, or weird hallway chaos without directly confronting anyone. Users should upload photos and short descriptions, and the apps AI should generate playful roast commentary about the scene. The tone should feel like a mixture of neighborhood watch, hall monitor satire, and group-chat humor. The goal is not cruelty but social pressure through comedy. The app should include a public leaderboard showing which dorm floors, apartments, kitchens, or anonymous offenders got roasted the most. Users should react, vote, add jokes, and escalate ongoing legendary mess situations into local campus lore. The visual design should feel like a fake municipal authority mixed with internet meme culture. Everyone should feel like they are participating in a ridiculous shared civilization project to maintain order in chaotic communal living spaces. $STYLE'

wait
echo "ALL DONE" >> "$HERE/_status.log"
