#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/landing-pages/vibes/one-bit-status"
cd "$HERE"

# Pin the publishing namespace explicitly so a stale `vibes-diy login`
# default (account swap, re-auth, CLI upgrade) cannot land deploys at the
# wrong user-slug. See src/pages/featured-apps/README.md for context.
USER_SLUG="og"

# Shared Terminal CRT style preamble — appended to every prompt to keep
# the cluster visually unified. Phosphor green on near-black, VT323
# monospace, scanline overlay, bracketed buttons, no rounded corners.
STYLE='STYLE — Terminal CRT phosphor display. Load Google Font VT323 (display=optional); body font is "VT323", monospace, font-size 18px, line-height 1.4. Background --bg oklch(0.16 0 0) near-black. Surface --terminal oklch(0 0 0 / 0.85). Foreground --green oklch(0.87 0.30 142) phosphor-green; muted --green-dim oklch(0.87 0.30 142 / 0.4); borders --green-border oklch(0.87 0.30 142 / 0.3); faint fills --green-faint oklch(0.87 0.30 142 / 0.1); pure --white oklch(1 0 0) reserved for accents. Apply text-shadow: 0 0 10px oklch(0.87 0.30 142 / 0.7) on h1/h2/key numbers. Add a fixed full-screen CRT overlay (repeating-linear-gradient horizontal scanlines, rgba(0,255,0,0.03), 1px every 3px, pointer-events none, z-index 99). Add a 3px-tall scan-line sweep bar (gradient bottom-fade) animating top→bottom over 8s infinite, z-index 100. Status indicators are 6px round dots: active = solid --green with box-shadow 0 0 8px green-glow; inactive = --green-dim, no glow. Section labels uppercase, letter-spacing 0.1em, --green-dim, prefixed "SYS:" or "STATUS:" or "FEED:" where appropriate. Inputs and textareas: transparent bg, 1px solid --green-border, square corners, monospace caret blinks. Buttons render as bracketed text "[ RUN ]" "[ PING ]" "[ CLEAR ]" with hover changing to filled-green-on-black inverse. No emoji icons; use ASCII symbols or unicode block characters (▌ █ ░ ▒ ● ○ ▲ ▼ →). No rounded corners on cards, only on the 6px dots. Card frames are 1px --green-border with --terminal background. Build single-file React. Persist all writes as Fireproof docs via useFireproof; render past entries below the input as a reverse-chronological list inside the Terminal aesthetic.'

gen() {
  local slug="$1"; shift
  local prompt="$*"
  ( "$TSX" "$MAIN" generate --user-slug "$USER_SLUG" --app-slug "$slug" "$prompt" >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) &
}

: > "$HERE/_status.log"

# === 01 LIGHT'S ON — one bit per friend ===
# SKIP (already deployed): gen lights-on "Light's On — a one-bit presence app for a small friend group (2–10 people). The whole UI is a single screen. Top: an input for your name (saved to localStorage on first visit). Below: a big square button that toggles your own status between LIGHT ON (filled green dot, glowing) and LIGHT OFF (dim hollow circle). Below that: a flat row of every member's name with their dot indicator next to it, sorted alphabetically. Each toggle writes a Fireproof doc { name, on: bool, ts }; we always read the latest doc per name to compute the live state. Below the row, a scrollback feed shows the last 30 toggle events: \"jchris — LIGHT ON 2m ago\". Treat ts as authoritative; refresh every 5s via Fireproof live query. No groups, no rooms, no settings. The whole app is a single bit per person. $STYLE"

# === 02 PET STATUS BOARD ===
gen pet-status-board "Pet Status Board — for a household of 1–4 pet owners broadcasting their current pet's mood. Add a pet at the top (name, species). Each pet card has a single big tap target cycling through a fixed set of states with one tap: LOAF, ROCKET, DEMANDING, ASLEEP, ZOOMIES, CLOAKED. Each tap writes a Fireproof doc { petId, state, ts, by }. The pet card always shows the latest state large, with a pixel-art ASCII glyph rendered in monospace (e.g. LOAF = a small ASCII blob, ROCKET = an arrow). Below: a chronological state log for that pet. Below the cards: a household feed of the last 50 state transitions across all pets. No notifications. No editing past states. State changes only roll forward. $STYLE"

# === 03 SLEEP OVERLAP VISUALIZER ===
gen sleep-overlap "Sleep Overlap Visualizer — for a friend group of 3–8 people who want to know when 3+ are simultaneously awake. Each user enters their name and their typical wake/sleep hours (start hour 0–23, end hour 0–23, supports overnight ranges). Save profile as a Fireproof doc, one per user. Render a 24-hour horizontal timeline with each member as a row showing a green-bar block for their awake hours. Below: a single overlap row computed live: for each hour 0–23 show how many members are awake, render hours with overlap >= 3 as a saturated green bar, otherwise dim green. Highlight the current hour with a vertical scanline. Show three big readout numbers: \"AWAKE NOW: 4 / 6\", \"NEXT OVERLAP IN: 2h\", \"PEAK OVERLAP: 5 (22:00 UTC)\". A toggle switches between local timezones and UTC. List recent profile edits below as a feed. $STYLE"

# === 04 READING-RIGHT-NOW ROOM ===
gen reading-room "Reading-Right-Now Room — a presence-as-bookmark app for a small book-loving friend group. Each member submits one current book at a time: title, author, current page. Submitting writes a Fireproof doc { name, title, author, page, ts }. The latest doc per name is the live state. Render a single column of cards, one per member, each showing: name, book title (large, glowing green), author (dim), and a horizontal progress bar with current page over a user-supplied total page count (default 300). Pages are typed in by the user and updated by tapping a +1, +5, +10 page button on your own card. Below the cards: a feed of the last 40 page-bumps and book switches: \"meno bumped 'Annihilation' p.142 → 168 (15m ago)\". Add a single textarea per card for an optional one-line passage quote saved alongside the page bump. No comments, no replies, no following — just shared bookmarks. $STYLE"

# === 05 WHAT I'M COOKING ===
gen what-im-cooking "What I'm Cooking — a live stovetop status feed for a 3–10 person foodie group. Each user has a single \"now cooking\" slot. The input has three fields: dish name, current step (e.g. \"sweating onions\", \"deglazing\", \"resting\"), and ETA in minutes. Submitting writes a Fireproof doc { name, dish, step, eta_minutes, started_ts }. The latest doc per name represents their live cooking state; clearing the slot writes { name, idle: true, ts }. Render the kitchen feed as a vertical list of active cooks, each row: name, dish (glowing), current step (dim), and a live countdown to ETA computed from started_ts. When ETA hits zero, the row flashes \"PLATING\" until the user clears or updates. Below the feed: a 100-row scrollback log of step transitions. Add a row of stove-emoji-ish ASCII art (e.g. 'BURNER 1: ▓▓▓░' showing four burners with ascii heat gauges based on step type — heuristic: 'sweating' = low, 'searing' = high). Tone: voyeurism + dinner ideas, not a recipe app. $STYLE"

# === 06 NAP DECLARATION ===
gen nap-declaration "Nap Declaration — a single-button broadcast for a friend group. The home screen has a giant button: [ DECLARE NAP ]. Tapping it opens a one-line input for ETA in minutes (default 25, presets 15/25/45/90). Submitting writes a Fireproof doc { name, ts_start, eta_minutes }. The user's status flips to NAPPING and a live countdown shows on their card. The button changes to [ WAKE ] which writes { name, woke: true, ts }. Other members see a feed of who's currently napping with live countdowns. Below: a 7-day nap log per user with average nap length and longest streak of consecutive nap days. A toggle on each user's own card 'AUTO-SNOOZE NOTIFICATIONS' just writes a flag — there is no actual notification integration, the flag is for vibes. Show a small histogram of nap start hours below the feed. No comments, no reactions. $STYLE"

# === 07 DOG WALK ANNOUNCER ===
gen dog-walk-announcer "Dog Walk Announcer — a neighborhood broadcast for dog owners walking right now. User profile: name + dog name (saved once). The home screen has [ START WALK ] which opens a small form: route description (one short string), expected duration in minutes. Submitting writes a Fireproof doc { walker, dog, route, eta_minutes, ts_start, joined: [] }. Active walks render as cards in a feed: \"jchris + Pickles — around the cemetery, ETA 20m, started 4m ago\". Each card has a [ JOIN ] button that appends the current user's name to the joined array on that walk doc and shows them as joining. The walker can [ END WALK ] which writes { walkId, ended_ts }. Past walks show below as a scrollback log with route, duration, joiners. Add a small streak counter per walker (consecutive days walked) and a 'longest-walk' leaderboard. No GPS, no maps — just typed-in routes. $STYLE"

# === 08 VIRTUAL CAFE CO-WORKING ===
gen virtual-cafe "Virtual Cafe Co-working — presence + Pomodoro timer + ambient feed for a small remote-work crew (2–8 people). Each user enters their name and a current task (one short string). The home screen shows a shared 25-min timer with [ START SESSION ] [ PAUSE ] [ END ]. Starting writes a Fireproof doc per user { name, task, ts_start, status: 'focusing' }; ending writes { name, ts_end, completed: true }. The cafe view is a grid of seats: each occupied seat shows the member's name, their current task, and a small monospace timer counting down their session. A separate column shows ambient chatter: a textarea where members can drop one short line of context (\"deep in the SQL\", \"breaking for tea\"). Each chatter line is a Fireproof doc; show only the last 20. Below the grid: a session log per user with completed Pomodoros today and current streak. The whole point: co-presence without a video call. No chat threads. $STYLE"

# === 09 HOME-IN-5 ROOMMATE PING ===
gen home-in-5 "Home-in-5 — a one-button doorbell-to-housemates ping. The full app is a single household of 2–6 named roommates set up once on first visit. The home screen is one giant button: [ HOME IN 5 ]. Tapping writes a Fireproof doc { from, eta_minutes: 5, ts }. A live feed shows the last 20 pings with relative times: \"jchris — home in 5 (3m ago)\". Each incoming ping pulses for 5 minutes after it arrives (CSS animation on its row), then dims to history. Variant buttons let the sender pick [ HOME IN 15 ] [ HOME IN 30 ] [ HOME NOW ] [ STAYING OUT ]. Each writes a typed ping doc. Below the feed: a small per-roommate pattern view — last 7 days of ping types as a row of glyphs (5/15/30/now/stay), and a count of pings sent this week. No replies, no chat. $STYLE"

# === 10 NOON WAVE ===
gen noon-wave "Noon Wave — a synchronized 30-second daily check-in for a friend group. Every weekday at local noon, the app's home screen shows a 30-second window during which every member can drop one short line and one selfie-shaped ASCII glyph (rendered from a small set: ヽ(•‿•)ノ, (•_•), ¯\\_(ツ)_/¯, ◉_◉, etc) plus a single emoji-tier mood word (UP, FLAT, FRIED, CHILL, BUZZED). Submitting during the window writes a Fireproof doc { name, line, glyph, mood, ts }. After 12:00:30, the window closes — late submissions are saved but tagged late: true and rendered dim. The day's wave page shows all six members in a row with their submissions; missing members render as empty placeholder cards. Calendar view below shows the last 30 days as a 6-column × 30-row grid of dots: solid green = on time, dim = late, hollow = missed. The point: one synchronized minute per day, no other interaction surface. $STYLE"

wait
echo "ALL DONE" >> "$HERE/_status.log"
