#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/landing-pages/vibes/nahui-ollin"
cd "$HERE"

# Pin the publishing namespace explicitly so a stale `vibes-diy login`
# default cannot land deploys at the wrong user-slug.
USER_SLUG="og"

STYLE='Elder Codex skin. Load Google Fonts: Cinzel:wght@400;600;700 + Cormorant+Garamond:ital,wght@0,400;0,600;1,400 (display=optional). Body font: Cormorant Garamond, Georgia, serif, 1.05rem. Headings: Cinzel, all-caps, letter-spacing 0.12em. Background: near-black obsidian #06040a. Panel/card bg: #12100a. Card borders: 1px solid #2a2015. Body text: #d4c5a0. Muted text: #8a7a60. Primary accent gold #c9a84c — use on headings, active states, key borders, with text-shadow glow 0 0 16px rgba(201,168,76,0.4). Secondary accent jade/turquoise #00c9a7 for interactive elements and CTAs. Tertiary accent terracotta #c0522a for dates and numbers. Thin 4px gold gradient bar at very top of page. Sharp corners only (border-radius: 0). Buttons: bordered Cinzel uppercase small text "[ CONSULT ]" "[ INVOKE ]" with hover: gold fill, obsidian text. Input fields: transparent bg, 1px bottom border gold, glow on focus. Horizontal dividers: thin 1px #2a2015 with centered ◈ glyph in gold. Tone: a living Mesoamerican codex — ancient calendar instruments that still compute. Single-file React with useFireproof; persist data as codex scroll entries below the live interface.'

gen() {
  local slug="$1"; shift
  local prompt="$*"
  ( "$TSX" "$MAIN" generate --user-slug "$USER_SLUG" --app-slug "$slug" "$prompt" \
    >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) &
}

: > "$HERE/_status.log"

gen day-sign-calc "Day Sign Oracle — calculate and display the Tonalpohualli (260-day Aztec sacred calendar) day sign and number for any Gregorian date. The Tonalpohualli has 20 day signs cycling: Cipactli (Crocodile), Ehecatl (Wind), Calli (House), Cuetzpalin (Lizard), Coatl (Serpent), Miquiztli (Death), Mazatl (Deer), Tochtli (Rabbit), Atl (Water), Itzcuintli (Dog), Ozomatli (Monkey), Malinalli (Grass), Acatl (Reed), Ocelotl (Jaguar), Cuauhtli (Eagle), Cozcacuauhtli (Vulture), Ollin (Movement/Earthquake), Tecpatl (Flint), Quiahuitl (Rain), Xochitl (Flower). Each pairs with a number 1-13; full cycle = 260 days. Anchor date: August 13 1521 CE = 1 Cipactli. App: date picker input; calculate day sign via modular arithmetic from anchor; display the day sign name in Nahuatl and English, its number, its ruling deity (Cipactli=Tonacatecuhtli, Ehecatl=Quetzalcoatl, Calli=Tepeyollotl, Cuetzpalin=Huehuecoyotl, Coatl=Chalchiuhtlicue, Miquiztli=Tecciztecatl, Mazatl=Tlaloc, Tochtli=Mayahuel, Atl=Xiuhtecuhtli, Itzcuintli=Mictlantecuhtli, Ozomatli=Xochipilli, Malinalli=Patecatl, Acatl=Tezcatlipoca, Ocelotl=Tlazolteotl, Cuauhtli=Xipe Totec, Cozcacuauhtli=Itzpapalotl, Ollin=Xolotl, Tecpatl=Chalchiuhtotolin, Quiahuitl=Tonatiuh, Xochitl=Xochiquetzal), and a brief one-line augury. Store past queries as Fireproof docs in a scroll archive below. $STYLE"

gen aztec-solar-wheel "Aztec Solar Wheel — show today's position in the Xiuhpohualli (365-day Aztec solar calendar). The calendar has 18 veintenas (20-day months): Atlcahualo, Tlacaxipehualiztli, Tozoztontli, Huey Tozoztli, Toxcatl, Etzalcualiztli, Tecuilhuitontli, Huey Tecuilhuitl, Tlaxochimaco, Xocotl Huetzi, Ochpaniztli, Teotleco, Tepeilhuitl, Quecholli, Panquetzaliztli, Atemoztli, Tititl, Izcalli — plus 5 Nemontemi days. For today's veintena show: its name, presiding deity, day range, and a one-line ritual description. Display: which day within the veintena (1–20), days remaining in this veintena, days until Nemontemi. A circular annual progress ring visualization. Fireproof logs each visit. $STYLE"

gen calendar-round-timer "Calendar Round — visualize the 52-year Calendar Round (Xiuhmolpilli). The round is formed by the interlocking of the 260-day Tonalpohualli and 365-day Xiuhpohualli — 18,980 unique days before any date combination repeats. At the end of each round, the New Fire ceremony was performed: all fires extinguished, people waited in darkness, priests drilled new fire on a hilltop. Show: today's position in the current 52-year cycle, the date the current cycle started, countdown in years/months/days/hours to the next Calendar Round completion and New Fire. A dual-ring dial visualization: inner ring = Tonalpohualli progress, outer ring = Xiuhpohualli progress, rotating slowly. Fireproof stores saved Calendar Round moments. $STYLE"

gen year-bearer "Year Bearer — in the Aztec calendar, only four Tonalpohualli day signs can begin a solar year: Acatl (Reed, East), Tecpatl (Flint, North), Calli (House, West), Tochtli (Rabbit, South). They cycle in order with a number 1–13; each year-bearer+number combo repeats every 52 years. The current year's bearer determines its general character and direction. App: display the current year's bearer sign (name in Nahuatl and English), its number, its associated cardinal direction and color, its presiding deity, and a traditional augury. Below: a 52-cell grid showing the full bearer cycle with the current year highlighted and past years dimmed. Let users click any Gregorian year (1521–2100) to see its bearer. Fireproof tracks queried years. $STYLE"

gen nemontemi-watch "Nemontemi Watcher — the Nemontemi are the 5 hollow, unlucky epagomenal days that end the Aztec 365-day solar year (days 361–365). During Nemontemi, no new undertakings were started, no fires kindled, no celebrations held — to be born in Nemontemi was a very bad omen. App: calculate the exact countdown (days / hours / minutes / seconds) to the next Nemontemi period based on an Aztec calendar anchor. When the Nemontemi period is active, the entire interface dims: background darkens, gold accents dim to grey, a solemn banner appears reading 'NEMONTEMI — FIVE HOLLOW DAYS'. Show which hollow day it is (1 of 5 through 5 of 5) and the traditional character of each. After Nemontemi ends, show countdown to the next one. Fireproof logs each Nemontemi observation with timestamp. Tone: reverent, quiet, slightly ominous. $STYLE"

gen five-suns-cards "Five Suns — interactive cards for the five Aztec creation eras. Each sun was a world created and destroyed before ours. The five suns: 1) Nahui Ocelotl (4 Jaguar) — Tezcatlipoca's sun, populated by earth-giants, eaten by jaguars at the end; 2) Nahui Ehecatl (4 Wind) — Quetzalcoatl's sun, people ate acorns, destroyed by hurricane wind, survivors became monkeys; 3) Nahui Quiahuitl (4 Rain) — Tlaloc's sun, people ate water-maize, destroyed by rain of fire, survivors became turkeys and butterflies; 4) Nahui Atl (4 Water) — Chalchiuhtlicue's sun, people ate wild seeds, destroyed by flood for 52 years, survivors became fish; 5) Nahui Ollin (4 Movement) — the present sun, created at Teotihuacan when the gods sacrificed themselves, will end in earthquake. Display as five large ornate cards with: sun name in Nahuatl and English, presiding deity, dominant element, destruction method, what survived, and a one-paragraph mythic retelling. Click to flip card and reveal the destruction scene in dramatic prose. Fireproof tracks which suns have been read. $STYLE"

gen ollin-glyph "Ollin Glyph — an animated visualization of the Nahui Ollin / Ollin glyph (Movement/Earthquake), the central symbol of the Aztec Sun Stone. The glyph is a cross or butterfly shape: four curved petal-forms extending from a center, each containing a smaller circle, together representing the four previous suns arranged around the fifth. Render the glyph in SVG: gold strokes on obsidian, clean geometric forms. The glyph rotates very slowly (one full rotation per 60 seconds). On click/tap: an earthquake animation — the four petals shift and crack apart along radial lines, pause, then reform (CSS animation, 2 seconds). On device tilt (DeviceOrientation API): the glyph tilts in 3D perspective following the device angle. The center circle pulses slowly like a heartbeat (scale 1.0 to 1.08, 3-second cycle). Below: the glyph name 'OLLIN — MOVEMENT' in Cinzel Decorative, and a line from the myth: 'And the fifth sun trembles. It moves. It is us.' Optional second mode: tap each petal to label it with its sun era name. Fireproof logs earthquake activations with timestamp. $STYLE"

gen directional-cosmos "Directional Cosmos — the Aztec universe was divided into four cardinal quadrants, each with a color, deity, tree, bird, day sign group, and character. East (Tlapallan) — color red, deity Tlaloc (later Tonatiuh), tree Palo Mulato, bird quetzal, day signs Acatl/Ocelotl/Cuauhtli/Cozcacuauhtli/Ollin, meaning dawn/life/abundance. North (Mictlampa) — color black, deity Tezcatlipoca, tree Cypress, bird screech owl, day signs Tecpatl/Quiahuitl/Xochitl/Cipactli/Ehecatl, meaning death/cold/the underworld. West (Cihuatlampa) — color white, deity Quetzalcoatl, tree Ceiba, bird hummingbird, day signs Calli/Cuetzpalin/Coatl/Miquiztli/Mazatl, meaning women/twilight/the dead sun. South (Huitztlampa) — color blue-yellow, deity Huitzilopochtli/Mayahuel, tree Willow, bird parrot, day signs Tochtli/Atl/Itzcuintli/Ozomatli/Malinalli, meaning abundance/sacrifice/the sun at noon. Center — fire, deity Xiuhtecuhtli, the axis of the universe connecting all levels. Display as an interactive compass mandala: five zones (N/S/E/W/Center). On click, each zone expands to reveal its full attributes in an overlay panel. The center always shows a slow fire ember animation. $STYLE"

gen patron-deity-finder "Patron Deity Finder — in Aztec belief, the day of your birth in the Tonalpohualli determined your patron deity. The 20 patron deities by day sign: Cipactli=Tonacatecuhtli (sustenance/fertility), Ehecatl=Quetzalcoatl (wind/knowledge/arts), Calli=Tepeyollotl (jaguar/caves/echo), Cuetzpalin=Huehuecoyotl (trickster/music), Coatl=Chalchiuhtlicue (water/jade/purification), Miquiztli=Tecciztecatl (moon/cowardice-turned-courage), Mazatl=Tlaloc (rain/agriculture), Tochtli=Mayahuel (pulque/agave/400 rabbits), Atl=Xiuhtecuhtli (fire/turquoise/time), Itzcuintli=Mictlantecuhtli (death/the underworld), Ozomatli=Xochipilli (flowers/summer/pleasure), Malinalli=Patecatl (medicine/healing herbs), Acatl=Tezcatlipoca (smoking mirror/fate/darkness), Ocelotl=Tlazolteotl (filth/purification/sexuality), Cuauhtli=Xipe Totec (renewal/spring/flaying), Cozcacuauhtli=Itzpapalotl (obsidian butterfly/fate), Ollin=Xolotl (lightning/dogs/twins/the underworld guide), Tecpatl=Chalchiuhtotolin (plague/divine punishment/the jeweled turkey), Quiahuitl=Tonatiuh (the sun/sacrifice/warriors), Xochitl=Xochiquetzal (beauty/weaving/lovers/flowers). Enter a Gregorian birth date; compute the Tonalpohualli day sign using standard modular arithmetic (anchor: Aug 13 1521 = 1 Cipactli); display patron deity name, domain, symbol, and a personal augury. Archive past readings in Fireproof. $STYLE"

gen new-fire-ceremony "New Fire Ceremony — at the end of every 52-year Calendar Round, all fires across the Aztec empire were extinguished. People climbed to their rooftops and waited in absolute darkness, fearing the sun would not rise and monsters would descend to devour humanity. Priests climbed Huixachtlan hill; if the stars moved, they drilled a new fire on the chest of a sacrificed captive and carried it by torch to every temple and home. This app is a shared group ritual: one person creates a room and sets the fire time (any future moment). All joined members see a dark screen: pure obsidian background, a subtle star field (CSS animation, slow drift). A centered live countdown to the fire time in large Cinzel numerals. When the host clicks IGNITE: a single ember appears at center screen, grows for 3 seconds, then erupts into a full conflagration animation (CSS: layered radial-gradient pulses in amber, crimson, gold, white-core — no canvas needed). All members see it simultaneously via Fireproof sync. The ceremony is logged as a Fireproof doc with timestamp and participant count. Past ceremonies listed in a 'Completed Rounds' archive. Tone: the darkest screen that becomes the brightest light. $STYLE"

wait
echo "ALL DONE" >> "$HERE/_status.log"
