#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/landing-pages/vibes/run-of-show"
cd "$HERE"

# Pin the publishing namespace explicitly so a stale `vibes-diy login`
# default (account swap, re-auth, CLI upgrade) cannot land deploys at the
# wrong user-slug. See src/pages/featured-apps/README.md for context.
USER_SLUG="og"

# Shared Broadsheet style preamble — strict black-on-white grid, hairline borders,
# all-caps tiny labels, Helvetica Neue. Operational paper-trail aesthetic.
STYLE='STYLE — Broadsheet. Body font Helvetica Neue / Helvetica / Arial sans-serif. Background pure white #fff, foreground pure black #000, single hairline borders 1px solid #000 between every grid cell. NO rounded corners anywhere — every box, button, input, and card is sharp-cornered. Layout in a max-width 1000px column with a vertical 1px black border on the left and right of the page. Hero uses a 200px / 1fr / 200px three-column band with thin black borders, a giant outline-only display headline (font-size clamp(3rem,10vw,8rem), font-weight 900, -webkit-text-stroke 2px #000, color transparent, letter-spacing -0.04em, uppercase). Section headers are tiny: font-size 0.55rem–0.7rem, font-weight 700, uppercase, letter-spacing 0.08–0.12em. Filled section labels use background #000 / color #fff. Tables use a strict CSS grid: each row is a grid-template-columns line with 1px black row borders and 1px black cell borders; row hover inverts to bg:#000 color:#fff. Forms use bottom-bordered inputs only (border:none; border-bottom:1px solid #000; transparent bg) with tiny uppercase labels. Buttons are square: padding 0.75rem 1.5rem, background:#fff, 1px solid #000, color #000, uppercase 0.65rem 700-weight letter-spacing 0.08em, hover inverts to bg:#000 color:#fff. Checkboxes are 16px black-bordered squares that fill black when checked. Toggles are 36×18 black-bordered tracks with a 12×12 sliding knob. NO color outside #000, #fff, and #666 for muted secondary text. NO emoji or icons — use small black SVG strokes or simple unicode arrows (›, →, ▲) where needed. Persist all writes as Fireproof docs via useFireproof; render past entries below the form as a strict bordered table. Single-file React.'

gen() {
  local slug="$1"; shift
  local prompt="$*"
  ( "$TSX" "$MAIN" generate --user-slug "$USER_SLUG" --app-slug "$slug" "$prompt" >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) &
}

: > "$HERE/_status.log"

# === 01 IPO ROADSHOW CHOREOGRAPHY ===
gen ipo-roadshow "IPO Roadshow Choreography — a multi-city, multi-meeting day-of operational app. The user (an IR lead or banker) sets up a roadshow: list of cities (NYC, Boston, SF, etc), and per-city meetings as rows: time, investor name, attendees, location/room, status. Submitting a roadshow writes a Fireproof doc { roadshowId, name, cities, meetings: [...] }. The home view is a strict black-and-white grid: today\\'s city banner across the top, then the meetings table with columns TIME / INVESTOR / ROOM / STATUS / NOTES. Each meeting row click expands inline notes (textarea) and a status toggle that cycles UPCOMING → IN PROGRESS → DONE → MISSED. Status changes write Fireproof docs { meetingId, status, ts, by }. A second view shows ALL CITIES at a glance: rows of cities with progress dots. A start-of-day timer counts down to the first meeting. Three top stats: meetings done / total, investors covered, road score (% on time). $STYLE"

# === 02 EARNINGS CALL REHEARSAL CARDS ===
gen earnings-rehearsal "Earnings Call Rehearsal Cards — for IR teams prepping the CEO/CFO for an earnings call. The user creates a deck of Q&A cards: each card has a question, a short answer (the prepared reply), a key talking points list (3 bullets), and a difficulty 1–5. Cards are saved as Fireproof docs. Rehearsal mode: shuffles the deck, shows one card front (just the question) with a [ REVEAL ] button; tapping shows the answer and bullets. Below: [ NAILED IT ] / [ NEEDS WORK ] / [ SKIP ] buttons that record outcomes per card per session. After running through, the app shows a session summary: nailed/needs-work counts, the questions still flagged needs-work, and average self-score. A persistent left rail lists all cards by difficulty, sortable. Filter by topic tag. Export the full deck to clipboard as plain text. Tone: dry IR rehearsal tool — not gameified, just clear. $STYLE"

# === 03 CUSTOMER SITE-VISIT MINUTE BOARD ===
gen site-visit-minutes "Customer Site-Visit Minute Board — an 8-hour exec visit run-of-show for an account team. The user pre-loads the day as a list of timed slots: 09:00 arrival, 09:30 demo block A, 10:30 product deep-dive, 12:00 lunch with executive, 14:00 architecture session, 16:00 close-out. Each slot has owner(s), location/room, and brief notes. Saving the day writes a Fireproof doc with the full slot list. Day-of view: a vertical timeline with a moving NOW line. Each slot row shows time, owner, location, status (UPCOMING / LIVE / DONE), and a single-tap [ HANDOFF ] button that marks the slot done and timestamps the transition. Tapping a slot opens a quick-notes textarea where any team member can drop in-room observations (saved as separate timestamped Fireproof docs linked to the slot). Below the timeline: a live participant board showing who is currently in which slot and a running clock since the last handoff. Print view (Cmd-P friendly): strict black-and-white printable rundown sheet. $STYLE"

# === 04 M&A SIGNING-DAY SCRIPT ===
gen ma-signing-day "M&A Signing-Day Script — choreography for signing day, when lawyers, bankers, PR, and EAs are on a 4-hour clock. The user sets up the day as a numbered task list: each task has a description, owner, dependencies (which task IDs must complete first), expected duration in minutes, and current status (PENDING / IN PROGRESS / BLOCKED / DONE). Saving writes a Fireproof doc per task. The home view is a tightly-bordered grid: column 1 task number, 2 description, 3 owner, 4 deps satisfied? (✓ or ✗), 5 status, 6 elapsed. Tasks unlock in real-time as their deps complete. Owners click a [ START ] button on their row which writes a status doc and starts an elapsed timer; clicking [ DONE ] writes a completion. A live banner across the top shows: NEXT BLOCKED, TASKS REMAINING, ELAPSED OF 4:00. A drift alarm fires (visual, not audio) if total elapsed exceeds budget. Below: a chronological audit log of every status change with timestamp and actor. $STYLE"

# === 05 PRODUCT LAUNCH WAR ROOM ===
gen launch-war-room "Product Launch War Room — coordination dashboard for a global product launch with a PR embargo timer and regional rollout dependencies. The user sets up: launch name, embargo lift time (UTC), regions to roll to (US-East, EU, APAC, etc), and a list of go-live items per region (e.g. press release live, blog post, social posts, in-app banner). Each item is a Fireproof doc with region, name, owner, status (PENDING / READY / SHIPPED / FAILED). Home: a giant countdown to embargo lift, a region grid (one column per region) showing all items per region as small status squares. Above the grid, three numbers: ITEMS SHIPPED, BLOCKED, ON DECK. An incident feed at the bottom: any team member can drop a one-line incident note (e.g. "press release stuck in CMS approval") tagged to a region; incidents are timestamped Fireproof docs. After embargo lift, the timer flips to ELAPSED. Buttons per item: [ MARK READY ] / [ SHIP IT ] / [ FAIL ]. Tone: serious launch ops, no gamification. $STYLE"

# === 06 BOARD MEETING RUNDOWN ===
gen board-rundown "Board Meeting Rundown — a corporate secretary\\'s tool for tracking motions, vote tallies, and materials cued during a board meeting. The user pre-loads the agenda as ordered items: each item has a title, presenter, materials links (pasted as URLs), expected duration, and a flag whether it requires a board vote. Saving writes a Fireproof doc per agenda item. Live meeting mode: presenter and a stopwatch per item; the secretary clicks [ NEXT ITEM ] to advance. For vote items, the screen shows YEA / NAY / ABSTAIN counters (incremented by tapping; one tap per vote) and a [ RECORD VOTE ] button that locks the tally to a Fireproof doc. The agenda renders as a strict numbered list with ✓ / – / ☐ status glyphs. Below: a chronological motion log with timestamps, presenter, motion text, and final vote tally. Print-friendly minutes export at the bottom (a [ EXPORT MINUTES ] button generates a plain-text minutes file). $STYLE"

# === 07 CRISIS COMMS LIVE PLAYBOOK ===
gen crisis-comms "Crisis Comms Live Playbook — choreography for the first 6 hours of a corporate crisis (PR, legal, exec). The user opens the app, names the incident, and the playbook auto-creates a fixed task list: T+0 ASSESS, T+15 LEGAL HOLD, T+30 EXEC ALIGN, T+45 EMPLOYEE NOTICE DRAFT, T+1H FIRST EXTERNAL STATEMENT, T+2H CUSTOMER NOTICE, T+4H PRESS BRIEFING, T+6H POST-MORTEM. Each row has owner (assigned at start), status, and a notes field. The clock starts immediately on incident open. Statuses are written as Fireproof docs with timestamps. A side panel "decision log" lets any role drop a one-line decision tagged with a category (LEGAL / EXEC / COMMS / HR). A second tab "approved language" stores the canonical drafted statements (Fireproof docs of statement-version + approver + timestamp). The home grid is two columns: incident timeline (left) and decision log (right), with a top banner showing TIME ELAPSED and OPEN DECISIONS count. $STYLE"

# === 08 LAYOFF DAY CHOREOGRAPHY ===
gen layoff-day "Layoff Day Choreography — for the HR / IT / legal / comms team coordinating a layoff day. Pre-load: the cohort (anonymized as employee IDs E001, E002, ... or first-name-last-initial), each row carrying scheduled meeting time, manager, IT badge revoke time, Slack/email cutoff time, severance package version, and current status (SCHEDULED / IN MEETING / NOTIFIED / IT DONE / FAREWELL SENT). Each status update writes a Fireproof doc. The home view is a strict grid sorted by meeting time. Each row shows the latest status; clicking a row expands inline detail (manager notes, package version diff, escalation flag). A top banner: SCHEDULED / NOTIFIED / IT DONE counters. A second pane: ESCALATIONS, where any flag (e.g. "employee request to keep laptop", "manager unavailable") creates a small Fireproof escalation doc that the legal/HR lead can resolve. No emoji, no celebratory language anywhere. The whole tone is procedural and respectful — the app makes timing precise so nothing slips. $STYLE"

# === 09 ALL-HANDS CUE SHEET ===
gen all-hands-cue "All-Hands Cue Sheet — for the chief of staff running an all-hands meeting. Pre-load the agenda: speaker order with their slide cue (deck section name), demo cues (which feature is being shown), and Q&A moderation slots. Each slot has expected duration. Saving writes Fireproof docs. Live mode: a giant timer for the current speaker, a [ NEXT ] button to advance, and a bright-but-still-monochrome [ TIME WARNING ] indicator that flashes when the speaker is at 80% of their budget. A separate Q&A queue: anyone (the moderator clicks ADD-FROM-CHAT) drops a question with attribution; the moderator can reorder by drag (or up/down arrow buttons) and mark questions as ANSWERED / SKIPPED. Below: a running cue log of every advance and mod action. Stats footer: total elapsed, scheduled remaining, drift in minutes (positive = behind). $STYLE"

# === 10 INVESTOR DAY RUNDOWN ===
gen investor-day "Investor Day Rundown — an 8-hour live-event rundown with executive rotations. Pre-load: the event has named segments (KEYNOTE, PRODUCT BLOCK, FINANCIALS, OPS BLOCK, FIRESIDE, CLOSING) each with a primary speaker, a back-up, expected start, expected duration, and a stage location. Each segment is a Fireproof doc. Live view: a 3-column board EXECS / SEGMENTS / STAGES with the live NOW line crossing all three. Segments occupy time blocks; their owner-exec is highlighted as "ON STAGE" on the executives column for the segment\\'s duration. A handoff pane shows the next two transitions (who hands off to whom, in which room). Drift counter at top. A side action log captures any chief-of-staff intervention (e.g. "moved Q&A 5 minutes earlier", "swapped fireside speaker"). All actions are timestamped Fireproof docs. Tone: producer in a control booth, not a slide deck. $STYLE"

wait
echo "ALL DONE" >> "$HERE/_status.log"
