import { type } from "arktype";

// Single source of truth for the notification-type union. Reused by the live
// fan-out event (`EvtUserNotification`), the persisted `Notifications` row
// (`notificationRow`), the emit input (`emitNotificationInput`), the read API,
// and the frontend TYPE_MAP. Adding a type here is the one place to change.
// `vibe-remixed` and `dm-received` are reserved for later phases (remix
// first-consumer / DM migration) and intentionally added now so the union is
// stable across phases.
export const notificationTypeEnum = type(
  "'build-complete' | 'build-failed' | 'vibe-published' | 'comment-posted' | 'request-approved' | 'request-revoked' | 'vibe-remixed' | 'dm-received'"
);
export type NotificationType = typeof notificationTypeEnum.infer;

export const EvtUserNotification = type({
  type: "'vibes.diy.evt-user-notification'",
  notificationType: notificationTypeEnum,
  ownerHandle: "string",
  appSlug: "string",
});
export type EvtUserNotification = typeof EvtUserNotification.infer;
export function isEvtUserNotification(obj: unknown): obj is EvtUserNotification {
  return !(EvtUserNotification(obj) instanceof type.errors);
}

// Build notifications (`build-complete` / `build-failed`) fan out to every one of
// the user's connections — including the originating tab/device — so clicking the
// browser notification can focus whichever device it was clicked on and route it to
// the vibe. Other notification types still skip the originator on fan-out.
export function isBuildNotification(notificationType: string): boolean {
  return notificationType === "build-complete" || notificationType === "build-failed";
}

// Pages without a vibe connection (My Vibes, Memberships, Messages, Settings) open a
// dedicated, lightweight notification connection pinned to a STABLE per-user shard so
// the UserNotify subscriber set stays bounded (one shard per user). Regular chat
// (codegen) connections use random-UUID shards; only shards with this prefix are
// allowed to register as user-notification subscribers, so an ephemeral codegen shard
// can never leak into the fan-out set.
export const USER_NOTIFY_SHARD_PREFIX = "notify-user-";

export function userNotifyShardFor(userId: string): string {
  return `${USER_NOTIFY_SHARD_PREFIX}${userId}`;
}

export function isUserNotifyShard(shard: string): boolean {
  return shard.startsWith(USER_NOTIFY_SHARD_PREFIX);
}

export const ReqSubscribeUserNotificationsRaw = type({
  type: "'vibes.diy.req-subscribe-user-notifications'",
});
export type ReqSubscribeUserNotificationsRaw = typeof ReqSubscribeUserNotificationsRaw.infer;
export function isReqSubscribeUserNotificationsRaw(obj: unknown): obj is ReqSubscribeUserNotificationsRaw {
  return !(ReqSubscribeUserNotificationsRaw(obj) instanceof type.errors);
}

export const ResSubscribeUserNotifications = type({
  type: "'vibes.diy.res-subscribe-user-notifications'",
  status: "'ok'",
});
export type ResSubscribeUserNotifications = typeof ResSubscribeUserNotifications.infer;
export function isResSubscribeUserNotifications(obj: unknown): obj is ResSubscribeUserNotifications {
  return !(ResSubscribeUserNotifications(obj) instanceof type.errors);
}

// A persisted Notifications row as read back from the table. Columns match
// sqlNotifications / sqlNotifications (sqlite + pg). `body` is self-contained
// so a list view renders straight from the row with no second query;
// `targetRef` is the optional pointer a per-type renderer MAY hydrate.
export const notificationRow = type({
  id: "string",
  userId: "string",
  notificationType: notificationTypeEnum,
  ownerHandle: "string",
  appSlug: "string",
  body: "string",
  "actorHandle?": "string | null",
  "actorUserId?": "string | null",
  "targetRef?": "unknown",
  dedupeKey: "string",
  created: "string",
  "readAt?": "string | null",
});
export type NotificationRow = typeof notificationRow.infer;
export function isNotificationRow(obj: unknown): obj is NotificationRow {
  return !(notificationRow(obj) instanceof type.errors);
}

// Input to `emitNotification()`. The recipient is `userId`; `dedupeKey` is the
// idempotency key (unique per (userId, dedupeKey)). `id`/`created`/`readAt` are
// generated by the emit helper, so they are not part of the input.
export const emitNotificationInput = type({
  userId: "string",
  notificationType: notificationTypeEnum,
  ownerHandle: "string",
  appSlug: "string",
  body: "string",
  "actorHandle?": "string",
  "actorUserId?": "string",
  "targetRef?": "unknown",
  dedupeKey: "string",
});
export type EmitNotificationInput = typeof emitNotificationInput.infer;
