export const c = {
  pageBg: "bg-[#EEE]",
  cardBg: "bg-white",
  headerBg: "bg-[#BACD32]",
  navBg: "bg-[#71AD44]",
  bodyText: "text-[#4A4A4A]",
  border: "border-[#4A4A4A]",
  pinkBg: "bg-[#CD6C0C]",
  eventCard: "bg-[#BACD32] rounded-2xl border-4 border-[#4A4A4A] p-4 shadow-lg",
  favCard: "bg-[#71AD44] rounded-2xl border-4 border-[#4A4A4A] p-4 shadow-lg",
  shiftCard: "bg-[#71AD44] rounded-2xl border-4 border-[#4A4A4A] p-4",
  schedDay: "mb-6 bg-[#71AD44] rounded-2xl border-4 border-[#4A4A4A] p-4",
  schedShift: "rounded-xl border-2 border-[#4A4A4A] p-3 bg-[#BACD32]",
  schedEvent: "rounded-xl border-2 border-[#4A4A4A] p-3 bg-white",
  input: "p-3 border-4 border-[#4A4A4A] rounded-xl font-bold text-[#4A4A4A] bg-white",
  navBtn: (active) =>
    `px-6 py-3 font-bold rounded-2xl border-4 border-[#4A4A4A] transition-all ${active ? "bg-[#4A4A4A] text-white" : "bg-white text-[#4A4A4A] hover:bg-[#BACD32]"}`,
  btnPink: "bg-[#CD6C0C] text-white font-bold py-3 px-6 rounded-2xl border-4 border-[#4A4A4A] hover:opacity-90 transition-all",
  btnCyan: "bg-[#71AD44] text-white font-bold py-3 px-6 rounded-2xl border-4 border-[#4A4A4A] hover:opacity-90 transition-all",
  badge: "bg-[#CD6C0C] text-white px-3 py-1 rounded-full text-sm font-bold border-2 border-[#4A4A4A]",
  favToggleOn: "p-3 rounded-2xl border-4 border-[#4A4A4A] font-bold transition-all bg-[#CD6C0C] text-white hover:opacity-90",
  favToggleOff: "p-3 rounded-2xl border-4 border-[#4A4A4A] font-bold transition-all bg-white text-[#4A4A4A] hover:bg-[#BACD32]",
  linkBtn: "p-3 bg-white text-[#4A4A4A] rounded-2xl border-4 border-[#4A4A4A] hover:bg-[#BACD32] transition-all",
  noteArea: "w-full p-2 border-2 border-[#4A4A4A] rounded-xl resize-none text-sm text-[#4A4A4A] bg-white",
  deleteBtn: "p-3 bg-[#B22222] text-white rounded-2xl border-2 border-[#4A4A4A] hover:opacity-80 transition-all",
  noteBox: "mt-2 p-2 bg-white rounded-lg border-2 border-[#4A4A4A]",
  shiftForm: "bg-[#BACD32] rounded-2xl border-4 border-[#4A4A4A] p-6 mb-6",
  spinner: "w-4 h-4 border-2 border-[#4A4A4A] rounded-full animate-spin border-t-transparent",
  readOnlyBanner: "mt-2 bg-white text-[#4A4A4A] px-3 py-2 rounded-lg text-sm font-bold border-2 border-[#4A4A4A]",
};

export const viewerTagStyle = {
  "--accent": "#CD6C0C",
  "--accent-text": "#fff",
  "--card-bg": "rgba(255,255,255,0.85)",
  "--border": "#4A4A4A",
  "--text": "#4A4A4A",
  border: "3px solid #4A4A4A",
  borderRadius: 999,
  fontWeight: 700,
  fontSize: 16,
};
