#!/usr/bin/env bash
#
# setup-cloud-browser.sh — make chrome-devtools MCP "just work" in the
# Claude Code cloud / remote execution environment.
#
# The cloud container ships a Playwright Chromium under /opt/pw-browsers but
# NOT a Google Chrome at the path chrome-devtools-mcp expects, and headful
# Chrome there needs three accommodations the MCP server doesn't apply on its
# own: a sandbox opt-out (it runs as root), a virtual X display, and a TLS
# downgrade so the agent egress proxy can read the SNI from Chrome's
# ClientHello. This script wires all of that up idempotently.
#
# It is a NO-OP on a normal local workstation (real Chrome, no /opt/pw-browsers),
# so it is safe to run from a SessionStart hook on every session.
#
# Background + rationale: agents/cloud-browser-setup.md
set -euo pipefail

CHROMIUM_LINK="/opt/pw-browsers/chromium"          # symlink → …/chrome-linux/chrome
CHROME_SHIM="/opt/google/chrome/chrome"            # path chrome-devtools-mcp looks for
DISPLAY_NUM="${VIBES_BROWSER_DISPLAY:-:99}"

log() { printf 'setup-cloud-browser: %s\n' "$*" >&2; }

# --- Detect the cloud browser environment -----------------------------------
# Only the cloud container has the Playwright Chromium symlink. On a local
# workstation this is absent, so we bow out and let real Chrome be used.
if [ ! -e "$CHROMIUM_LINK" ]; then
  log "no /opt/pw-browsers Chromium — assuming local workstation, nothing to do."
  exit 0
fi

# --- 1. Install the Chrome shim ---------------------------------------------
# chrome-devtools-mcp (channel "stable") launches $CHROME_SHIM. We point that
# at the Playwright Chromium and inject the flags it needs. The Chromium path
# is resolved at runtime so the shim survives Playwright version bumps that
# change the chromium-<rev> directory name.
mkdir -p "$(dirname "$CHROME_SHIM")"
cat > "$CHROME_SHIM" <<'SHIM'
#!/usr/bin/env bash
# Auto-generated by scripts/setup-cloud-browser.sh — do not edit by hand.
set -euo pipefail

# Resolve the real Chromium binary (follows the version-pinned symlink).
CHROME_BIN="$(readlink -f /opt/pw-browsers/chromium)"

# A virtual display: headful Chrome refuses to start without an X server.
export DISPLAY="${DISPLAY:-:99}"

args=(
  # Running as root in a container: the default sandbox can't initialize.
  --no-sandbox
  --disable-dev-shm-usage
)

# Route through the agent egress proxy when one is configured, and cap TLS at
# 1.2. The proxy peeks at the TLS ClientHello to enforce per-host egress
# policy; Chrome's TLS 1.3 ClientHello (post-quantum key share, GREASE) is
# large enough to span multiple TCP segments, which the proxy's SNI parser
# can't reassemble — it resets the connection (ERR_CONNECTION_CLOSED). TLS 1.2
# yields a compact single-segment ClientHello the proxy parses cleanly. The
# proxy is pass-through, so Chrome still validates the real origin cert via its
# built-in roots — no verification is disabled.
if [ -n "${HTTPS_PROXY:-${https_proxy:-}}" ]; then
  args+=(
    --proxy-server="${HTTPS_PROXY:-$https_proxy}"
    --disable-quic
    --ssl-version-max=tls1.2
  )
fi

exec "$CHROME_BIN" "${args[@]}" "$@"
SHIM
chmod +x "$CHROME_SHIM"
log "installed Chrome shim at $CHROME_SHIM → $(readlink -f "$CHROMIUM_LINK")"

# --- 2. Start a virtual display ---------------------------------------------
if pgrep -f "Xvfb ${DISPLAY_NUM}" >/dev/null 2>&1; then
  log "Xvfb already running on ${DISPLAY_NUM}."
elif command -v Xvfb >/dev/null 2>&1; then
  Xvfb "${DISPLAY_NUM}" -screen 0 1920x1080x24 >/tmp/xvfb-cloud-browser.log 2>&1 &
  # Give the server a moment to create the socket before anything connects.
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    [ -S "/tmp/.X11-unix/X${DISPLAY_NUM#:}" ] && break
    sleep 0.2
  done
  log "started Xvfb on ${DISPLAY_NUM}."
else
  log "WARNING: Xvfb not found — headful Chrome will fail to launch."
fi

log "ready. chrome-devtools MCP can now navigate the web."
