#!/usr/bin/env bash
#
# setup-cloud-browser.sh — make chrome-devtools MCP "just work" in the
# Claude Code cloud / remote execution environment.
#
# The cloud container ships a Playwright Chromium under /opt/pw-browsers but
# NOT a Google Chrome at the path chrome-devtools-mcp expects, and headful
# Chrome there needs three accommodations the MCP server doesn't apply on its
# own: a sandbox opt-out (it runs as root), a virtual X display, and a TLS
# downgrade so the agent egress proxy can read the SNI from Chrome's
# ClientHello. This script wires all of that up idempotently.
#
# It is a NO-OP on a normal local workstation (real Chrome, no /opt/pw-browsers),
# so it is safe to run from a SessionStart hook on every session.
#
# Background + rationale: agents/cloud-browser-setup.md
set -euo pipefail

CHROME_SHIM="/opt/google/chrome/chrome"            # path chrome-devtools-mcp looks for
DISPLAY_NUM="${VIBES_BROWSER_DISPLAY:-:99}"

log() { printf 'setup-cloud-browser: %s\n' "$*" >&2; }

# Resolve the Playwright Chromium binary. Prefer the stable /opt/pw-browsers/
# chromium symlink, but fall back to the newest versioned install
# (…/chromium-<rev>/chrome-linux/chrome) so images that ship only the versioned
# path with no symlink still work. Echoes the path, or nothing if absent.
resolve_chromium() {
  local p
  p="$(readlink -f /opt/pw-browsers/chromium 2>/dev/null || true)"
  if [ -n "$p" ] && [ -x "$p" ]; then
    printf '%s\n' "$p"
    return 0
  fi
  p="$(ls -1d /opt/pw-browsers/chromium-*/chrome-linux/chrome 2>/dev/null | sort -V | tail -n1 || true)"
  if [ -n "$p" ] && [ -x "$p" ]; then
    printf '%s\n' "$p"
  fi
}

# --- Detect the cloud browser environment -----------------------------------
# Only the cloud container has a Playwright Chromium. On a local workstation it
# is absent, so we bow out and let real Chrome be used.
CHROMIUM_BIN="$(resolve_chromium)"
if [ -z "$CHROMIUM_BIN" ]; then
  log "no Playwright Chromium under /opt/pw-browsers — assuming local workstation, nothing to do."
  exit 0
fi

# --- 1. Install the Chrome shim ---------------------------------------------
# chrome-devtools-mcp (channel "stable") launches $CHROME_SHIM. We point that
# at the Playwright Chromium and inject the flags it needs. The shim resolves
# the Chromium binary the same way at runtime, so it survives Playwright version
# bumps that change the chromium-<rev> directory name. DISPLAY_NUM is baked in
# so VIBES_BROWSER_DISPLAY is honored by the launched Chrome too.
mkdir -p "$(dirname "$CHROME_SHIM")"
{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n' '# Auto-generated by scripts/setup-cloud-browser.sh — do not edit by hand.'
  printf 'DEFAULT_DISPLAY=%q\n' "$DISPLAY_NUM"
  cat <<'SHIM'
set -euo pipefail

# Resolve the real Chromium binary: prefer the stable symlink, fall back to the
# newest versioned install (matches the setup script's discovery).
CHROME_BIN="$(readlink -f /opt/pw-browsers/chromium 2>/dev/null || true)"
if [ -z "${CHROME_BIN:-}" ] || [ ! -x "$CHROME_BIN" ]; then
  CHROME_BIN="$(ls -1d /opt/pw-browsers/chromium-*/chrome-linux/chrome 2>/dev/null | sort -V | tail -n1 || true)"
fi

# A virtual display: headful Chrome refuses to start without an X server. An
# explicit DISPLAY in the environment wins; otherwise use the baked default.
export DISPLAY="${DISPLAY:-$DEFAULT_DISPLAY}"

args=(
  # Running as root in a container: the default sandbox can't initialize.
  --no-sandbox
  --disable-dev-shm-usage
)

# Route through the agent egress proxy when one is configured, and cap TLS at
# 1.2. The proxy peeks at the TLS ClientHello to enforce per-host egress
# policy; Chrome's TLS 1.3 ClientHello (post-quantum key share, GREASE) is
# large enough to span multiple TCP segments, which the proxy's SNI parser
# can't reassemble — it resets the connection (ERR_CONNECTION_CLOSED). TLS 1.2
# yields a compact single-segment ClientHello the proxy parses cleanly. The
# proxy is pass-through, so Chrome still validates the real origin cert via its
# built-in roots — no verification is disabled.
if [ -n "${HTTPS_PROXY:-${https_proxy:-}}" ]; then
  args+=(
    --proxy-server="${HTTPS_PROXY:-$https_proxy}"
    --disable-quic
    --ssl-version-max=tls1.2
  )
fi

exec "$CHROME_BIN" "${args[@]}" "$@"
SHIM
} > "$CHROME_SHIM"
chmod +x "$CHROME_SHIM"
log "installed Chrome shim at $CHROME_SHIM → $CHROMIUM_BIN"

# --- 2. Start a virtual display ---------------------------------------------
# Socket name is X<n> where <n> is the display number without the leading ':'
# and without any screen suffix (e.g. ':99.0' → '99').
disp_num="${DISPLAY_NUM#:}"
disp_num="${disp_num%%.*}"
xvfb_socket="/tmp/.X11-unix/X${disp_num}"

if pgrep -f "Xvfb ${DISPLAY_NUM}" >/dev/null 2>&1; then
  log "Xvfb already running on ${DISPLAY_NUM}."
elif command -v Xvfb >/dev/null 2>&1; then
  Xvfb "${DISPLAY_NUM}" -screen 0 1920x1080x24 >/tmp/xvfb-cloud-browser.log 2>&1 &
  # Give the server a moment to create its socket before anything connects.
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    [ -S "$xvfb_socket" ] && break
    sleep 0.2
  done
  if [ -S "$xvfb_socket" ]; then
    log "started Xvfb on ${DISPLAY_NUM}."
  else
    log "WARNING: Xvfb did not come up on ${DISPLAY_NUM} (socket ${xvfb_socket} missing) — see /tmp/xvfb-cloud-browser.log."
  fi
else
  log "WARNING: Xvfb not found — headful Chrome will fail to launch."
fi

log "ready. chrome-devtools MCP can now navigate the web."
