#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/landing-pages/vibes/run-the-place"
cd "$HERE"
gen() {
  local slug="$1"; shift
  local prompt="$*"
  ( "$TSX" "$MAIN" generate --app-slug "$slug" "$prompt" >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) &
}
: > "$HERE/_status.log"

gen "listing-pipeline-board" "Build a single-file React app called Listing Pipeline Board for a small real-estate office (3-15 agents). Use Fireproof via useFireproof from 'use-fireproof' so the whole office sees the same board live across desktops and tablets. Five fixed kanban columns: Lead, Showing, Offer Submitted, Under Contract, Closed. Each card shows property address (bold), lead/client name, agent assigned (initials chip), and last touch date in 'days ago' style ('3d ago' turns amber after 5d, red after 10d to nudge accountability). Add-card form at the top of each column with address, lead, agent dropdown. Cards drag between columns using HTML5 drag and drop; on drop, update the doc { type:'listing', address, lead, agent, stage, lastTouch, createdAt }. Per-column header shows count and total estimated commission if entered. A 'touched today' button on each card bumps lastTouch. Clean office palette: navy + cream + a little gold for Closed. Mobile-friendly columns become horizontal scroll on small screens. No login, no AI."

gen "shift-reconciliation" "Build a single-file React app called Shift Reconciliation Board for restaurants and small retail shops. Use Fireproof via useFireproof from 'use-fireproof' for live sync between the closer's tablet and the manager's phone. At top, today's date and a list of shifts in progress. Each closer adds their reconciliation row: name, station (Bar/Server/Register), cash counted (input), credit-card total from POS (input), tip pool contribution, comps/voids, and the POS-reported shift total to compare. App computes deposit envelope total = cash counted - tip pool - opening float (configurable, default 200), and displays a 'discrepancy' field = (cash + cards) - POS total. If |discrepancy| > 5 dollars, highlight the row red and require a note. Each row has a big 'Sign Off' button that records signedBy + signedAt; once signed the row locks. Manager view shows totals across all shifts and an envelope number to write on the bag. Doc shape { type:'shift', date, closer, station, cash, cards, tipPool, voids, posTotal, note, signedBy, signedAt }. Tone: clean, accountable, almost clinical. Mobile-first, big tap targets."

gen "sunday-school-roster" "Build a single-file React app called Sunday School Roster for a small religious-ed program (3-15 teachers). Use Fireproof via useFireproof from 'use-fireproof' so the director and teachers share the same roster live. Three tabs: Classes, Students, This Sunday. Classes tab: list of classes with grade level, teacher name, room number, plus an inline 'add class' form. Students tab: roster of children grouped by class, with parent contact, allergy/notes field. This Sunday tab: shows today's (or next Sunday's) lesson per class with curriculum reference (e.g. 'Unit 4, Lesson 2: The Good Samaritan'), and an attendance check-off list for each class — tap a child to mark present, saves doc { type:'attendance', classId, studentId, sunday:'2026-05-03', present:true }. A small printable summary view at bottom: 'this week 24 of 31 students attended'. Lesson schedule editable inline. Warm, simple, friendly palette — soft blues and ivory, not childish. Mobile-friendly for teachers using phones in the classroom."

gen "trade-desk-handoff-log" "Build a single-file React app called Trade Desk Handoff Log for a small bond or equity trading desk (3-15 traders, multi-shift coverage). Use Fireproof via useFireproof from 'use-fireproof' for live sync across trader workstations. Each trader at end of shift posts a structured handoff entry with: trader name, shift (AM/PM/Overnight), open positions (free-text list), pending orders (list of {ticker, side, qty, limit, expiry}), key client touches (list of {client, summary}), and 'must-know' notes. Save as doc { type:'handoff', trader, shift, date, openPositions, pendingOrders, clientTouches, notes, ackBy:[], createdAt }. Display today's and yesterday's handoffs in reverse chronological cards. The incoming shift trader sees an 'Acknowledge Read' checkbox at the bottom of each handoff that adds their name+timestamp to ackBy. Handoffs without acks for >2hr highlight orange. Filter by trader and date. Tone: terminal-green-on-charcoal serious, monospace, dense rows. Desktop and tablet, big enough to read across the desk."

gen "front-desk-reservation-queue" "Build a single-file React app called Front Desk Reservation Queue for small appointment-based businesses — salons, Pilates studios, dental offices, small clinics. Use Fireproof via useFireproof from 'use-fireproof' so the front desk tablet and the practitioner's room device stay in sync. Today's view is a vertical timeline from open to close (configurable hours, default 8am-7pm, 15-min ticks). Slots show booked appointments as cards with client name, phone, service, duration, and practitioner. Tap an empty slot to add a walk-in: name + phone + service dropdown + duration. Each appointment has status buttons: Checked In, In Service, Done, No-Show. If now > scheduled start + 5min and status is still 'Booked', the card highlights amber 'running late'. A side panel lists today's stats: arrived, no-shows, walk-ins, currently in service. Doc shape { type:'appt', clientName, phone, service, durationMin, practitioner, start, status, createdAt }. Clean, calm front-desk palette — soft sage and cream, generous whitespace. Mobile and tablet first."

gen "prep-list-by-section" "Build a single-file React app called Prep List by Section for a restaurant kitchen (3-15 cooks). Use Fireproof via useFireproof from 'use-fireproof' for live sync between every station's tablet and the chef's office. Stations are columns: Sauté, Grill, Garde Manger, Pastry, Pantry (configurable). Each prep item is a card with: item name (e.g. 'demi-glace, 2 qt'), owner cook (assigned), due-time (e.g. 'by 4:30pm'), done checkbox, and a 'started' timestamp. Add form per column: item, owner dropdown, due time. Doc { type:'prep', station, item, owner, dueAt, started, doneAt, note, createdAt }. Items past due that aren't done turn red. A 'Chef View' toggle at top collapses all columns into one dense list sorted by due time, so the chef can spot misses before service. Bottom shows progress per station ('Sauté: 7/9 done'). Tone: tight, professional kitchen — chalkboard backgrounds, clipboard feel, big readable type for steamy hands. Mobile-first for tablets clipped to walls."

gen "closing-sign-off-checklist" "Build a single-file React app called Closing Sign-Off Checklist for storefronts, dental clinics, and Pilates studios — multi-person end-of-day close-out. Use Fireproof via useFireproof from 'use-fireproof' so manager and staff share the same closing list live. Settings panel lets the manager configure stations once: Lights, Safe, Alarm, Inventory, Trash, Back Door, Restrooms, etc. (free-add). Each closing day spawns a fresh checklist of those stations as rows. Each row: station name, responsible person dropdown, a check button, and an 'initials' input that must be filled to confirm. Saves doc { type:'signoff', date, station, by, initials, checkedAt }. The 'Lock Up' status indicator at the top is red until every station has both checked AND initialed, then turns green with a timestamp. A small history log shows last 14 nights' close-outs with who signed each station. Tone: serious, accountable, slightly clipboard — ivory paper, monospace headings, navy accents, no flourish. Mobile-first; meant to be tapped through quickly at end of night."

wait
echo "ALL DONE" >> "$HERE/_status.log"
