#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/landing-pages/vibes/house-rules"
cd "$HERE"
gen() {
  local slug="$1"; shift
  local prompt="$*"
  ( "$TSX" "$MAIN" generate --app-slug "$slug" "$prompt" >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) &
}
: > "$HERE/_status.log"

gen "farkle-scorekeeper" "Build a single-file React app for tracking Farkle dice game scores across rounds with house-rule variants. Use useFireproof from use-fireproof to sync games across devices. Input surface: a setup screen to add 2-6 player names, plus a settings panel with toggles for house rules (count 3 pairs as 1500, count straight 1-6 as 2500, lose-it-all on rolling zero, must-open-with-500). Saved doc shape: { type: 'game', _id, players: [{name, total, rounds: [{score, locked}]}], rules: {threePairs, straight, loseAll, mustOpen}, currentTurn, createdAt }. Visible UI: a scoreboard table with one column per player and a row per round, a big number-pad input for entering this turn's score, a 'Lock In' button per active player to commit the score, a running-total footer, and a winner banner when someone hits 10000. Tone: warm kitchen-table grandma energy, playful but legible at arm's length, large numbers."

gen "potluck-signup-board" "Build a single-file React app for a 'who's bringing what' potluck signup board. Use useFireproof from use-fireproof so the whole family can edit the same board live. Input surface: a host creates an event (title, date, location), guests add their name, the dish they're bringing, and toggle dietary chips (vegan, GF, nut-free, dairy-free). There's a 'claim a slot' affordance for missing categories: appetizer, main, side, dessert, drink. Saved doc shape: { type: 'signup', _id, event, guestName, dish, category, dietary: [], claimed, createdAt }. Visible UI: a header card with event details, four category columns (appetizer/main/dessert/drink) each showing claimed cards plus an empty 'claim this slot' button, a dietary-chip filter strip at top, and a running headcount. Tone: warm fridge-magnet hospitality, casual handwritten feel."

gen "gift-list-memory" "Build a single-file React app for tracking holiday gifts year over year. Use useFireproof from use-fireproof to sync the family gift archive across phones. Input surface: add a person (name, relation), then for each year add the gift you gave them with notes; on save, the app checks for near-duplicates from prior years and warns 'you almost gave Aunt Linda the same scarf you gave her in 2023'. Saved doc shape: { type: 'gift', _id, personName, year, gift, notes, createdAt } and { type: 'person', name, relation }. Visible UI: a left rail of people, a main panel showing one row per person with year columns (2022, 2023, 2024, 2025) each filled with the gift; an add-gift form at bottom with duplicate warning; a 'flag duplicates' toggle. Tone: cozy gentle reminder, soft ledger book vibe."

gen "holiday-card-roster" "Build a single-file React app for managing a holiday card mailing list. Use useFireproof from use-fireproof to sync the address book between you and your spouse. Input surface: quick-add form (name, address, relation) plus per-year status toggles for sent / received / skipped. Saved doc shape: { type: 'recipient', _id, name, address, relation, history: { '2023': 'sent', '2024': 'received', '2025': 'skipped' }, createdAt }. Visible UI: a sortable table — name, address, then one column per year showing colored chips (green sent, blue received, gray skipped); a 'quick add' inline row at the bottom; an export view that prints a clean address-label sheet. Tone: warm stationary-drawer practical, like a recipe-card box for stamps and good intentions."

gen "family-recipe-vault" "Build a single-file React app for collecting family recipes with optional voice-memo captures. Use useFireproof from use-fireproof to sync recipes across the family; use the Web Speech API (SpeechRecognition) to capture and transcribe spoken instructions. Input surface: a form for title, contributor, occasion tags (Thanksgiving/Hanukkah/Sunday/Birthday), ingredients list, and a 'hold to record' button that transcribes voice into the steps field. Saved doc shape: { type: 'recipe', _id, title, contributor, occasions: [], ingredients: [], steps, transcript, createdAt }. Visible UI: a left rail listing recipes grouped by occasion; a main panel showing the selected recipe with print-friendly typography; a record button with live transcription preview; tag chips for filtering. Tone: warm grandma's index-card box, generous serif, gentle browns and creams."

gen "shotgun-rotation-tracker" "Build a single-file React app for tracking who called shotgun on each leg of a road trip. Use useFireproof from use-fireproof so all passengers' phones see the same rotation. Input surface: add the trip roster (names), then per leg tap who's in the front seat; the app keeps a tally of front-seat legs per person and auto-suggests who is owed shotgun next. Saved doc shape: { type: 'trip', _id, name, roster: [], legs: [{from, to, shotgun, timestamp}], createdAt }. Visible UI: trip header, big 'next leg' card showing the auto-suggested person with a 'they accept' / 'override' button, a leg-by-leg history list, and a tally board ranking each rider by total shotgun legs taken vs owed. Tone: sun-bleached dashboard fairness, friendly diner-coffee road-trip energy."

gen "seder-run-of-show" "Build a single-file React app for hosting a holiday meal as a stage-managed run-of-show checklist (Seder, Thanksgiving, Christmas Eve). Use useFireproof from use-fireproof so the host and helpers see the same plan in real time, and so the layout can be saved as a reusable template for next year. Input surface: add ordered steps (time, action, who, notes — e.g. '5:45 start the brisket — Mom', '6:30 Karen reads the four questions'). Saved doc shape: { type: 'show', _id, name, steps: [{order, time, action, who, notes, done}], templateOf, createdAt }. Visible UI: a vertical timeline with checkboxes, drag-to-reorder steps, a 'who's up next' highlight banner, and a 'save as template' button at the top to clone the layout for next year's holiday. Tone: warm calm host-mode clipboard, gentle but precise."

wait
echo "ALL DONE" >> "$HERE/_status.log"
