#!/usr/bin/env python3
"""
Build the edu/syllabi compendium page body from harvest JSON files.
Run from the repo root or any directory — uses absolute paths.

Output: writes src/pages/edu/syllabi.hbs (creates/overwrites)
Usage: python3 research-humanities/build-compendium.py

NOTE: This script generates a self-contained webring page with its own CSS
(classes: .compendium-wrap, .institution, .filter-btn, etc.). The current
committed syllabi.hbs was manually redesigned after the script ran, using
different CSS classes (.wrap, .inst, .topbar, .fbtn). Re-running this script
will produce a working but visually different page — review the output before
committing. The layout key is "webring" so there is no double-HTML-wrapper
issue, but the topbar nav and dark header are not generated by this script.
"""

import json, glob, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "src/pages/edu/syllabi.hbs")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

institutions = []

for f in sorted(glob.glob(os.path.join(REPO, "research/harvest/*.json"))):
    with open(f) as fh:
        data = json.load(fh)
    inst = {
        "id": os.path.basename(f).replace(".json", ""),
        "name": data["source"],
        "location": data.get("location", ""),
        "region": data.get("region", ""),
        "domain": "STEM",
        "courses": []
    }
    for item in data.get("items", []):
        inst["courses"].append({
            "title": item["title"],
            "department": item.get("department", ""),
            "year": item.get("year", ""),
            "url": item.get("url", ""),
            "topics": item.get("topics", [])[:8]
        })
    institutions.append(inst)

for f in sorted(glob.glob(os.path.join(REPO, "research-humanities/harvest/*.json"))):
    with open(f) as fh:
        data = json.load(fh)
    inst = {
        "id": os.path.basename(f).replace(".json", ""),
        "name": data["source"],
        "location": data.get("location", ""),
        "region": data.get("region", ""),
        "domain": "Humanities",
        "courses": []
    }
    for item in data.get("items", []):
        inst["courses"].append({
            "title": item["title"],
            "department": item.get("department", ""),
            "year": item.get("year", ""),
            "url": item.get("url", ""),
            "topics": item.get("topics", [])[:8]
        })
    institutions.append(inst)

total = sum(len(i["courses"]) for i in institutions)


def build_institution_html(inst):
    domain_class = "stem" if inst["domain"] == "STEM" else "humanities"
    courses_html = []
    for c in inst["courses"]:
        topics_html = "".join(f'<span class="topic-tag">{t}</span>' for t in c["topics"])
        src_link = (
            f'<a href="{c["url"]}" target="_blank" rel="noopener" class="source-link">source ↗</a>'
            if c.get("url") else ""
        )
        dept = c.get("department", "")
        yr = c.get("year", "")
        meta = " · ".join(filter(None, [dept, str(yr) if yr else ""]))
        courses_html.append(f"""
        <div class="course-card" data-dept="{dept.lower()}" data-topics="{" ".join(c["topics"]).lower()}">
          <div class="course-header">
            <span class="course-title">{c["title"]}</span>
            {src_link}
          </div>
          {f'<div class="course-meta">{meta}</div>' if meta else ""}
          <div class="topics-row">{topics_html}</div>
        </div>""")

    return f"""
<section class="institution" id="{inst["id"]}" data-domain="{domain_class}">
  <div class="inst-header">
    <div class="inst-name">{inst["name"]}</div>
    <div class="inst-meta">
      {f'<span class="inst-location">{inst["location"]}</span>' if inst.get("location") else ""}
      <span class="domain-badge {domain_class}">{inst["domain"]}</span>
    </div>
  </div>
  <div class="courses-list">{"".join(courses_html)}
  </div>
</section>"""


institutions_html = "\n".join(build_institution_html(i) for i in institutions)

# Write the HBS page
page = f"""{{{{!--
{{
  "layout": "webring",
  "title": "Syllabus Corpus — Edu Portal | Vibes DIY",
  "description": "Browse {total} harvested syllabi across {len(institutions)} institutions. STEM and humanities courses with vocabulary topics and source links.",
  "ogUrl": "https://good.vibes.diy/edu/syllabi/",
  "source": "edu-syllabi-compendium"
}}
--}}}}

<style>
:root {{
  --black: #231F20;
  --ivory: #FFFFF0;
  --grid-gray: #CCCDC8;
  --ink: #1a1a1a;
  --muted: #5a5a5a;
  --stem-color: #0070c9;
  --hum-color: #7b3fa0;
  --tag-bg: rgba(35,31,32,0.07);
  --tag-border: rgba(35,31,32,0.15);
}}

.compendium-wrap {{
  max-width: 900px;
  margin: 0 auto;
  padding: 2rem 1.5rem 4rem;
  font-family: 'Alte Haas Grotesk', 'Helvetica Neue', sans-serif;
}}

.compendium-hero {{
  margin-bottom: 2.5rem;
  padding-bottom: 1.5rem;
  border-bottom: 2px solid var(--black);
}}

.compendium-hero h1 {{
  font-size: 2.5rem;
  font-weight: 700;
  line-height: 1.1;
  margin: 0 0 0.5rem;
}}

.compendium-hero p {{
  color: var(--muted);
  font-size: 1rem;
  margin: 0 0 1.5rem;
}}

.filter-bar {{
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
  align-items: center;
}}

.filter-bar input {{
  flex: 1;
  min-width: 200px;
  padding: 0.5rem 0.75rem;
  border: 2px solid var(--black);
  border-radius: 6px;
  font-size: 0.9rem;
  font-family: inherit;
  background: var(--ivory);
}}

.filter-btn {{
  padding: 0.45rem 0.9rem;
  border: 2px solid var(--black);
  border-radius: 6px;
  font-size: 0.8rem;
  font-family: inherit;
  font-weight: 700;
  cursor: pointer;
  background: var(--ivory);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}}

.filter-btn.active {{ background: var(--black); color: var(--ivory); }}
.filter-btn.stem-btn.active {{ background: var(--stem-color); border-color: var(--stem-color); color: white; }}
.filter-btn.hum-btn.active {{ background: var(--hum-color); border-color: var(--hum-color); color: white; }}

.stats-line {{
  font-size: 0.85rem;
  color: var(--muted);
  margin-top: 0.5rem;
}}

.institution {{
  margin-bottom: 2.5rem;
  border: 2px solid var(--black);
  border-radius: 12px;
  overflow: hidden;
  background: white;
}}

.institution[hidden] {{ display: none; }}

.inst-header {{
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 1.25rem;
  background: var(--grid-gray);
  border-bottom: 2px solid var(--black);
  flex-wrap: wrap;
  gap: 0.5rem;
}}

.inst-name {{
  font-weight: 700;
  font-size: 1.1rem;
}}

.inst-meta {{ display: flex; align-items: center; gap: 0.5rem; }}

.inst-location {{ font-size: 0.8rem; color: var(--muted); }}

.domain-badge {{
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
}}

.domain-badge.stem {{ background: var(--stem-color); color: white; }}
.domain-badge.humanities {{ background: var(--hum-color); color: white; }}

.courses-list {{ padding: 0.75rem; display: flex; flex-direction: column; gap: 0.5rem; }}

.course-card {{
  padding: 0.75rem 1rem;
  border: 1.5px solid var(--tag-border);
  border-radius: 8px;
  background: var(--ivory);
}}

.course-card[hidden] {{ display: none; }}

.course-header {{
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 0.5rem;
  margin-bottom: 0.25rem;
}}

.course-title {{ font-weight: 600; font-size: 0.95rem; line-height: 1.3; }}

.source-link {{
  font-size: 0.75rem;
  color: var(--stem-color);
  text-decoration: none;
  white-space: nowrap;
  flex-shrink: 0;
  margin-top: 0.1rem;
}}

.source-link:hover {{ text-decoration: underline; }}

.course-meta {{ font-size: 0.78rem; color: var(--muted); margin-bottom: 0.4rem; }}

.topics-row {{ display: flex; flex-wrap: wrap; gap: 0.3rem; }}

.topic-tag {{
  font-size: 0.72rem;
  padding: 0.15rem 0.45rem;
  background: var(--tag-bg);
  border: 1px solid var(--tag-border);
  border-radius: 4px;
  color: var(--ink);
}}

@media (max-width: 600px) {{
  .compendium-hero h1 {{ font-size: 1.8rem; }}
  .inst-header {{ flex-direction: column; align-items: flex-start; }}
}}
</style>

<div class="compendium-wrap">
  <div class="compendium-hero">
    <h1>Syllabus Corpus</h1>
    <p>{total} syllabi harvested from {len(institutions)} institutions — STEM and humanities. Browse by institution, filter by domain or keyword.</p>
    <div class="filter-bar">
      <input type="search" id="q" placeholder="Filter by title, department, or topic…" oninput="filterAll()">
      <button class="filter-btn active" id="btn-all" onclick="setDomain('all')">All</button>
      <button class="filter-btn stem-btn" id="btn-stem" onclick="setDomain('stem')">STEM</button>
      <button class="filter-btn hum-btn" id="btn-hum" onclick="setDomain('humanities')">Humanities</button>
    </div>
    <div class="stats-line" id="stats-line">Showing all {total} courses from {len(institutions)} institutions</div>
  </div>

  <div id="institutions-container">
{institutions_html}
  </div>
</div>

<script>
(function() {{
  var activeDomain = 'all';

  function setDomain(d) {{
    activeDomain = d;
    ['all','stem','hum'].forEach(function(k) {{
      var b = document.getElementById('btn-' + k);
      if (b) b.classList.toggle('active', k === (d === 'humanities' ? 'hum' : d));
    }});
    filterAll();
  }}

  function filterAll() {{
    var q = (document.getElementById('q').value || '').toLowerCase().trim();
    var sections = document.querySelectorAll('.institution');
    var totalVisible = 0;
    var instVisible = 0;

    sections.forEach(function(sec) {{
      var domainMatch = activeDomain === 'all' || sec.dataset.domain === activeDomain;
      if (!domainMatch) {{ sec.hidden = true; return; }}

      var cards = sec.querySelectorAll('.course-card');
      var anyCard = false;
      cards.forEach(function(card) {{
        var text = (card.querySelector('.course-title').textContent + ' ' +
                    card.dataset.dept + ' ' + card.dataset.topics).toLowerCase();
        var show = !q || text.includes(q);
        card.hidden = !show;
        if (show) {{ anyCard = true; totalVisible++; }}
      }});
      sec.hidden = !anyCard;
      if (anyCard) instVisible++;
    }});

    document.getElementById('stats-line').textContent =
      'Showing ' + totalVisible + ' course' + (totalVisible !== 1 ? 's' : '') +
      ' from ' + instVisible + ' institution' + (instVisible !== 1 ? 's' : '');
  }}

  window.filterAll = filterAll;
  window.setDomain = setDomain;
}})();
</script>
"""

with open(OUT, "w") as f:
    f.write(page)

print(f"Wrote {OUT}")
print(f"  {len(page)} chars, {len(institutions)} institutions, {total} courses")
