// Neo-brutalist style tokens for Rolling Today. Plain class-string map (no runtime
// deps) so every component can import the same vocabulary.
export const c = {
  page: "min-h-screen bg-[#FFF6E5] text-[#1A1A1A]",
  sun: "fixed -top-40 -right-40 w-[720px] h-[720px] rounded-full bg-[#FFCB05] opacity-50 pointer-events-none",
  grid: "fixed inset-0 pointer-events-none opacity-[0.12] bg-[length:48px_48px] bg-[linear-gradient(to_right,#1A1A1A_1px,transparent_1px),linear-gradient(to_bottom,#1A1A1A_1px,transparent_1px)]",
  wrap: "relative max-w-[920px] mx-auto px-5 sm:px-8 py-8 sm:py-12 z-10",
  header: "flex flex-wrap items-end justify-between gap-4 mb-8",
  brand: "flex items-baseline gap-3",
  brandMark: "inline-block w-3.5 h-3.5 rounded-full bg-[#E83D6F] border-2 border-[#1A1A1A]",
  brandText: "font-black uppercase tracking-tight text-[1.4rem] sm:text-[1.6rem] whitespace-nowrap",
  sub: "text-[0.7rem] uppercase tracking-[0.18em] text-[#1A1A1A]/70",
  nav: "flex gap-2 justify-end",
  navBtn:
    "inline-flex items-center gap-1.5 px-3 py-2 text-[0.78rem] font-bold uppercase tracking-wider bg-[#FFFDF5] border-[3px] border-[#1A1A1A] shadow-[3px_3px_0_#1A1A1A] hover:shadow-[5px_5px_0_#1A1A1A] hover:-translate-x-[2px] hover:-translate-y-[2px] active:shadow-none active:translate-x-[2px] active:translate-y-[2px] transition-all disabled:opacity-40 disabled:pointer-events-none",
  navBtnOn:
    "inline-flex items-center gap-1.5 px-3 py-2 text-[0.78rem] font-bold uppercase tracking-wider bg-[#E83D6F] text-[#FFF6E5] border-[3px] border-[#1A1A1A] shadow-[3px_3px_0_#1A1A1A] transition-all",
  // 1.5x header nav buttons (Prev / Today / Next / Friends), kept on one line.
  navBtnLg:
    "inline-flex items-center gap-2 px-[18px] py-3 text-[1.12rem] font-bold uppercase tracking-wider bg-[#FFFDF5] border-[3px] border-[#1A1A1A] shadow-[4px_4px_0_#1A1A1A] hover:shadow-[6px_6px_0_#1A1A1A] hover:-translate-x-[2px] hover:-translate-y-[2px] active:shadow-none active:translate-x-[2px] active:translate-y-[2px] transition-all disabled:opacity-40 disabled:pointer-events-none",
  navBtnLgOn:
    "inline-flex items-center gap-2 px-[18px] py-3 text-[1.12rem] font-bold uppercase tracking-wider bg-[#E83D6F] text-[#FFF6E5] border-[3px] border-[#1A1A1A] shadow-[4px_4px_0_#1A1A1A] transition-all",
  dateCard: "relative bg-[#1A1A1A] text-[#FFF6E5] border-[3px] border-[#1A1A1A] shadow-[6px_6px_0_#E83D6F] p-6 sm:p-8 mb-6",
  dateRow: "flex items-center justify-between gap-3 mb-2",
  dateLabel: "text-[0.7rem] uppercase tracking-[0.22em] text-[#FFCB05]",
  dateBig: "font-black text-[1.8rem] sm:text-[2.4rem] leading-none tracking-tight",
  count: "mt-3 text-[0.85rem] text-[#FFF6E5]/80",
  skip: "bg-[#FFCB05] text-[#1A1A1A] border-[3px] border-[#1A1A1A] shadow-[4px_4px_0_#1A1A1A] px-4 py-3 mb-6 font-bold text-[0.92rem] flex items-start gap-2",
  list: "flex flex-col gap-5",
  card: "bg-[#FFFDF5] border-[3px] border-[#1A1A1A] shadow-[5px_5px_0_#1A1A1A] p-5 sm:p-6 hover:shadow-[7px_7px_0_#1A1A1A] hover:-translate-x-[1px] hover:-translate-y-[1px] transition-all",
  timeRow: "flex flex-wrap items-baseline gap-x-3 gap-y-1 mb-2",
  time: "font-black text-[1.5rem] sm:text-[1.8rem] leading-none tracking-tight text-[#E83D6F]",
  endTime: "text-[0.85rem] text-[#1A1A1A]/70 font-bold",
  title: "font-black uppercase tracking-tight text-[1.3rem] sm:text-[1.55rem] leading-tight mb-3",
  badgeRow: "flex flex-wrap gap-2 mb-3",
  badge: "inline-flex items-center gap-1.5 px-2.5 py-1 text-[0.7rem] font-bold uppercase tracking-wider border-2 border-[#1A1A1A]",
  badgeAud: "bg-[#FFCB05]",
  badgeArea: "bg-[#7DD3FC]",
  badgeLoop: "bg-[#C6F08C]",
  venue: "flex items-start gap-2 text-[0.95rem] mb-1",
  venueText: "font-bold",
  addr: "text-[0.85rem] text-[#1A1A1A]/70 underline decoration-[#1A1A1A]/30 hover:decoration-[#E83D6F] hover:text-[#E83D6F]",
  organizer: "flex items-center gap-2 text-[0.85rem] text-[#1A1A1A]/75 mb-3",
  newsflash: "bg-[#FFCB05] border-2 border-[#1A1A1A] px-3 py-2 mb-3 text-[0.85rem] font-bold flex items-start gap-2",
  details: "text-[0.9rem] leading-relaxed text-[#1A1A1A]/85 whitespace-pre-wrap mb-4",
  actions: "flex flex-wrap gap-2 pt-3 border-t-2 border-dashed border-[#1A1A1A]/30",
  actionBtn:
    "inline-flex items-center gap-1.5 px-3 py-2 text-[0.78rem] font-bold uppercase tracking-wider border-[3px] border-[#1A1A1A] shadow-[3px_3px_0_#1A1A1A] hover:shadow-[5px_5px_0_#1A1A1A] hover:-translate-x-[2px] hover:-translate-y-[2px] active:shadow-none active:translate-x-[2px] active:translate-y-[2px] transition-all",
  actionCal: "bg-[#C6F08C]",
  actionLink: "bg-[#7DD3FC]",
  actionWeb: "bg-[#FFFDF5]",
  actionFavOff: "bg-[#FFFDF5] text-[#1A1A1A]",
  actionFavOn: "bg-[#E83D6F] text-[#FFFDF5]",
  favStrip: "flex items-center flex-wrap gap-x-3 gap-y-1 mb-3",
  favLabel: "text-[0.7rem] uppercase tracking-[0.18em] font-bold text-[#1A1A1A]/70",
  avatarPile: "flex items-center -space-x-2",
  avatar: "w-7 h-7 rounded-full border-2 border-[#1A1A1A] bg-[#FFFDF5] object-cover",
  avatarFallback:
    "w-7 h-7 rounded-full border-2 border-[#1A1A1A] bg-[#FFCB05] flex items-center justify-center text-[0.62rem] font-black uppercase",
  avatarMore: "ml-3 text-[0.78rem] font-bold text-[#1A1A1A]/70",
  noteArea:
    "w-full bg-[#FFF6E5] border-[3px] border-[#1A1A1A] px-3 py-2 text-[0.88rem] font-bold resize-none focus:outline-none focus:shadow-[3px_3px_0_#1A1A1A] transition-shadow",
  img: "w-full max-w-[280px] mt-1 mb-4 border-[3px] border-[#1A1A1A] shadow-[4px_4px_0_#1A1A1A] object-cover",
  empty: "text-center py-16 text-[1.1rem] font-bold",
  err: "bg-[#FFD8D8] border-[3px] border-[#E83D6F] shadow-[4px_4px_0_#E83D6F] px-4 py-3 mb-6 font-bold",
  foot: "mt-12 pt-6 border-t-2 border-[#1A1A1A]/30 text-[0.78rem] text-[#1A1A1A]/65 flex flex-wrap items-center gap-x-4 gap-y-2 justify-between",
  spin: "animate-spin",
  panel: "bg-[#FFFDF5] border-[3px] border-[#1A1A1A] shadow-[6px_6px_0_#7DD3FC] p-6 sm:p-8 mb-6",
  panelH: "font-black uppercase tracking-tight text-[1.3rem] mb-1",
  panelSub: "text-[0.8rem] text-[#1A1A1A]/70 mb-4",
  linkRow: "flex items-stretch gap-2 mb-6",
  linkInput: "flex-1 min-w-0 bg-[#FFF6E5] border-[3px] border-[#1A1A1A] px-3 py-2 text-[0.82rem] font-bold truncate",
  friendRow: "flex items-center gap-3 py-2 border-b-2 border-dashed border-[#1A1A1A]/20",
  signinCallout:
    "bg-[#1A1A1A] text-[#FFF6E5] border-[3px] border-[#1A1A1A] shadow-[5px_5px_0_#FFCB05] px-4 py-3 mb-6 font-normal text-[0.9rem] flex items-center gap-2",
};
