#!/usr/bin/env bash
set -u
TSX="/Users/jchris/code/fp/vibes.diy/vibes-diy/node_modules/.bin/tsx"
MAIN="/Users/jchris/code/fp/vibes.diy/vibes-diy/cli/main.ts"
HERE="/Users/jchris/code/fp/vibes.diy/vibes-diy/classroom-science"
cd "$HERE"

gen() {
  local slug="$1"; shift
  local prompt="$*"
  ( "$TSX" "$MAIN" generate --app-slug "$slug" "$prompt" >"$HERE/$slug.log" 2>&1; echo "DONE $slug exit=$?" >> "$HERE/_status.log" ) &
}

: > "$HERE/_status.log"

# === CARBON CYCLE — 2 takes ===

gen carbon-cycle-visualizer 'Interactive carbon cycle visualizer for high school earth science. Render a clear scientific diagram (using SVG) of the major carbon reservoirs as labeled rectangles laid out spatially: Atmosphere (top), Plants & Forests (mid-left), Soil (bottom-left), Ocean Surface (mid-right), Deep Ocean (bottom-right), Fossil Fuels (far bottom). Each reservoir shows its carbon stock in gigatons of carbon (GtC) as a number that updates live (atmosphere ~870 GtC, plants ~550, soil ~1500, ocean surface ~900, deep ocean ~37000, fossil fuels ~5000). Connect them with directional SVG arrows representing fluxes: photosynthesis (atmosphere→plants ~120 GtC/yr), respiration (plants→atmosphere ~120), decomposition (plants→soil ~60, soil→atmosphere ~60), ocean uptake (atmosphere→ocean ~92), ocean release (ocean→atmosphere ~90), fossil fuel combustion (fossil→atmosphere, slider-controlled), deforestation (plants→atmosphere, slider-controlled). Each arrow is labeled with its current flux rate in GtC/yr. Provide three sliders below the diagram: "Fossil emissions (GtC/yr)" 0–15 default 10, "Deforestation (GtC/yr)" 0–5 default 1.5, "Years to simulate forward" 0–100 default 0. As sliders change, run a simple Euler-step simulation in a useEffect updating reservoirs each year. Show a live readout of atmospheric CO2 in ppm (assume 1 GtC ≈ 0.47 ppm). Use a science-textbook color palette: forest green for plants, ocean blue for oceans, soil brown, gray atmosphere, near-black fossil fuels. Add a "Save scenario" button storing slider values + final reservoir snapshot + ppm as a Fireproof doc with a student-supplied label. List saved scenarios below in a "Lab notebook" panel showing each entry: label, year-end CO2 ppm, emissions setting. Single-file React with useFireproof. Tone: serious classroom tool, clean labeled SVG, no animations beyond optional pulsing arrow tips during simulation.'

gen carbon-cycle-flow 'Animated carbon cycle visualizer — a more visual take on the carbon cycle for middle-school earth science. Render six round reservoir bubbles arranged in a circle: Atmosphere, Plants, Soil, Surface Ocean, Deep Ocean, Fossil Fuels. Each bubble is sized in proportion to its current carbon stock and displays the GtC number inside. Between bubbles, animate small carbon particles (tiny dots) flowing along curved paths from source to sink at speeds proportional to the flux rate. Particle direction reverses when flux reverses. The student adjusts two big knobs: "Human emissions" and "Forest cover" (each 0–100%). Above the bubbles show the year (1850–2100, controlled by a Play/Pause/Reset button stepping through years). Below show atmospheric CO2 as a big readout in ppm. Use a friendly palette: pastel blues, greens, browns. Add a "Bookmark this moment" button that saves year + slider settings + ppm as a Fireproof doc; list past bookmarks below as cards. Build in single-file React; use SVG for bubbles and particle animation via requestAnimationFrame in useEffect. Tone: engaging, visual, BBC-Earth–style.'

# === PARABOLIC TRAJECTORY — 2 takes ===

gen parabolic-trajectory 'Projectile motion simulator for high school physics. The student adjusts three sliders: initial launch velocity v₀ (1 to 100 m/s, default 30), launch angle θ (0 to 90 degrees, default 45), and gravity g (0.1 to 25 m/s², default 9.81 for Earth, with quick-pick buttons for Moon 1.62, Mars 3.71, Jupiter 24.79). Render an SVG canvas with axes labeled in meters, gridlines every 10 meters. Above the canvas show the live equations: x(t) = v₀·cos(θ)·t and y(t) = v₀·sin(θ)·t − ½·g·t² with current numeric values plugged in. Below the canvas show three computed values updating live as sliders move: maximum height (m), horizontal range (m), and total flight time (s) using the closed-form formulas. As sliders change, redraw the parabolic trajectory as a faint dashed curve. A "Launch" button animates a small ball traveling along the trajectory at simulation speed (use requestAnimationFrame with t scaled to flight-time). Show a velocity vector arrow on the ball during flight, decomposed into horizontal and vertical components. Include a "Save shot" button that stores the slider config + range + height + time as a Fireproof doc with a student-supplied label. List saved shots below in a "Lab notebook" table with columns Label, v₀, θ, g, range, height, time, plus a "Replay" button per row that restores those settings. Single-file React with SVG. Tone: clean physics textbook, monospace numbers, navy + white aesthetic.'

gen projectile-launcher 'Multi-shot projectile motion lab. A more comparative take on projectile motion: the student configures one set of slider parameters (velocity, angle, gravity), clicks "Add shot", and the trajectory is added to a shared SVG canvas as a colored curve. Up to 6 shots can be displayed simultaneously, each in a different color, all drawn on the same axes for direct visual comparison. Each shot is labeled at its peak with its launch parameters. Below the canvas show a comparison table listing every shot with its v₀, θ, g, range, height, flight time. The student can delete individual shots or "Clear all". A "Save lab session" button stores the full set of shots as a Fireproof doc; past sessions are restorable from a dropdown. Encourage exploration: include three preset buttons "Compare angles" (loads three shots at 30°, 45°, 60° same v₀), "Compare gravities" (Earth/Mars/Moon same v₀ and θ), "Match the target" (places a target marker on the canvas; student tunes parameters to hit it). Single-file React with SVG. Tone: more playful than the basic simulator — a physics sandbox.'

# === INCLINED PLANE / FRICTION — 2 takes ===

gen ramp-friction-sim 'Inclined plane with friction — high school physics simulator. Render an SVG scene with a wedge-shaped ramp on the left rising to an angle the student controls, and a horizontal floor. A small block sits on the ramp surface. Three sliders control: ramp angle θ (0 to 60 degrees, default 30), coefficient of kinetic friction μ (0 to 1, default 0.3), and block mass m (1 to 20 kg, default 5). Draw a free-body diagram on the block with four labeled SVG arrows: gravity (vertical, magnitude m·g), normal force (perpendicular to ramp, magnitude m·g·cos θ), kinetic friction (along ramp opposing motion, magnitude μ·m·g·cos θ), and net force along ramp (magnitude m·g·sin θ − μ·m·g·cos θ when sliding). Each arrow shows its magnitude in newtons next to it. Above the canvas, render the algebra symbolically with current numerical values: "Net force = m·g·sin θ − μ·m·g·cos θ = X N" and "Acceleration a = g·(sin θ − μ·cos θ) = Y m/s²". Below the canvas, label the current state: "STATIC" (block at rest, friction balances gravity), "SLIDING" (block accelerating), or "BORDERLINE" (very close to threshold). A "Release block" button animates the block sliding down with the correct acceleration in real time, showing a live velocity readout. The block stops at the bottom of the ramp; show its final velocity. Add a "Save trial" button to persist current config + final velocity as a Fireproof doc; list trials in a "Lab notebook" table below with a Replay button per row. Single-file React with SVG. Tone: physics-textbook clean, graph-paper background, sharp arrow heads, monospace force labels.'

gen inclined-plane-block 'Inclined plane experiment lab — emphasis on running trials and collecting data, less on the diagram. The simulator shows a simpler ramp (no detailed free-body arrows on the block — just the block on the ramp), but provides rich experimental controls: ramp angle, surface choice (rubber/wood/ice/teflon — each presets a different μ), block mass. The student presses "Run trial" to release the block; the app times its slide and reports the measured acceleration and final velocity at the bottom. After at least 3 trials with varying angles or surfaces, the app generates a scatter plot of acceleration vs angle (or vs μ) so the student can see the relationship. Trials are saved automatically as Fireproof docs into the current "lab session" — the student names the session at the start. The app shows a results table with all trials and their measured values, plus an inferred best-fit line on the chart. Reset button starts a new session. Single-file React; use Chart.js via importmap or just custom SVG for the scatter plot. Tone: data-collection lab notebook, plain chart, stopwatch-clean UI.'

# === PERIODIC TABLE — 2 takes ===

gen periodic-table-explorer 'Interactive periodic table of the elements for high school chemistry. Render a full 18-column × 7-row periodic table grid using CSS grid (place lanthanides and actinides in their conventional spots below the main grid). Each element cell shows: atomic number (small, top-left), element symbol (large, centered), element name (small, below symbol), atomic mass (small, bottom). Color-code cells by category: alkali metals (red), alkaline earth (orange), transition metals (gold), post-transition metals (light gray), metalloids (yellow-green), nonmetals (green), halogens (teal), noble gases (purple), lanthanides (lavender), actinides (pink). Render a small color-coded legend below the table. When the student clicks any element, slide in a detail panel from the right showing: full name, symbol, atomic number, atomic mass, electron configuration (e.g., "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁵"), group and period, state at room temperature (solid/liquid/gas/synthetic), discovery year, and one fun fact (1–2 sentences). Hard-code accurate data for at least the first 36 elements (H through Kr). For elements 37+, show a placeholder cell with just symbol + atomic number. Add a search field above the table that highlights matching elements as the student types (by name, symbol, or number). Save "elements visited" as a Fireproof doc per session — show a "Lab notebook" panel below with the list. Single-file React. Tone: clean educational tool, accessible colors with sufficient contrast, large click targets suitable for tablets.'

gen element-quiz-table 'Periodic table quiz game — a quiz-first take on the periodic table. The student starts on a config screen choosing quiz mode: "Find by name", "Find by symbol", "Find by number", or "Mixed" — and difficulty (first 20 elements, first 36, or all 118). Click "Start" to enter quiz mode: render the periodic table with all element labels HIDDEN (just empty colored cells in correct positions). The app shows a prompt at the top like "Click Iron (Fe)" or "Click element 26" or just "Click Cl". The student clicks a cell; if correct, the cell reveals its label and turns green; if wrong, it briefly flashes red and the prompt repeats. After 10 questions, show a results screen with score, time, and a per-question breakdown. Save each session as a Fireproof doc with date, score, mode, difficulty, and time. List past sessions on the home screen with personal-best highlighting. The non-quiz "study mode" button shows the full labeled table for review with click-to-see-details. Hard-code the periodic table layout and element data for at least the first 36 elements. Single-file React. Tone: educational game, encouraging feedback, scoreboard aesthetic.'

wait
echo "ALL DONE" >> "$HERE/_status.log"
