name: "common ci run"
on:
#  pull_request_target:
#    types: [opened, synchronize, reopened]
#    branches: [main]

jobs:
  compile_test:
    runs-on: ubuntu-latest
    #environment:
    #  name: external-pr
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/base
