name: 'use-vibes-publish'
on:
  push:
    paths:
      - 'use-vibes/**/*'
    tags:
      - 'use-vibes@*'

jobs:
  compile_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: ${{ startsWith(github.ref, 'refs/tags/core@s') && 'staging' || startsWith(github.ref, 'refs/tags/core@p') && 'production' || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/runtime

      - name: install
        shell: bash
        run: pnpm install

      - name: build
        shell: bash
        run: pnpm build

      - name: lint
        shell: bash
        run: pnpm lint

      - name: cli-check
        shell: bash
        run: pnpm --filter use-vibes run check:cli

      - name: cli-test
        shell: bash
        run: pnpm --filter use-vibes-test run test:cli

      - uses: ./use-vibes/actions/publish
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
